package edu.jorbonism.nfclanders.enums

import edu.jorbonism.nfclanders.enums.CharacterType
import edu.jorbonism.nfclanders.enums.Game
import edu.jorbonism.nfclanders.enums.Playability

enum class Character(
    val id          : UInt,
    val game        : Game,
    val type        : CharacterType,
    val playability : Playability = Playability.Normal,
) {
    Whirlwind               (   0u, Game.SpyrosAdventure, CharacterType.Character     ),
    SonicBoom               (   1u, Game.SpyrosAdventure, CharacterType.Character     ),
    Warnado                 (   2u, Game.SpyrosAdventure, CharacterType.Character     ),
    LightningRod            (   3u, Game.SpyrosAdventure, CharacterType.Character     ),
    Bash                    (   4u, Game.SpyrosAdventure, CharacterType.Character     ),
    Terrafin                (   5u, Game.SpyrosAdventure, CharacterType.Character     ),
    DinoRang                (   6u, Game.SpyrosAdventure, CharacterType.Character     ),
    PrismBreak              (   7u, Game.SpyrosAdventure, CharacterType.Character     ),
    Sunburn                 (   8u, Game.SpyrosAdventure, CharacterType.Character     ),
    Eruptor                 (   9u, Game.SpyrosAdventure, CharacterType.Character     ),
    Ignitor                 (  10u, Game.SpyrosAdventure, CharacterType.Character     ),
    Flameslinger            (  11u, Game.SpyrosAdventure, CharacterType.Character     ),
    Zap                     (  12u, Game.SpyrosAdventure, CharacterType.Character     ),
    WhamShell               (  13u, Game.SpyrosAdventure, CharacterType.Character     ),
    GillGrunt               (  14u, Game.SpyrosAdventure, CharacterType.Character     ),
    SlamBam                 (  15u, Game.SpyrosAdventure, CharacterType.Character     ),
    Spyro                   (  16u, Game.SpyrosAdventure, CharacterType.Character     ),
    Voodood                 (  17u, Game.SpyrosAdventure, CharacterType.Character     ),
    DoubleTrouble           (  18u, Game.SpyrosAdventure, CharacterType.Character     ),
    TriggerHappy            (  19u, Game.SpyrosAdventure, CharacterType.Character     ),
    Drobot                  (  20u, Game.SpyrosAdventure, CharacterType.Character     ),
    DrillSergeant           (  21u, Game.SpyrosAdventure, CharacterType.Character     ),
    Boomer                  (  22u, Game.SpyrosAdventure, CharacterType.Character     ),
    WreckingBall            (  23u, Game.SpyrosAdventure, CharacterType.Character     ),
    Camo                    (  24u, Game.SpyrosAdventure, CharacterType.Character     ),
    Zook                    (  25u, Game.SpyrosAdventure, CharacterType.Character     ),
    StealthElf              (  26u, Game.SpyrosAdventure, CharacterType.Character     ),
    StumpSmash              (  27u, Game.SpyrosAdventure, CharacterType.Character     ),
    DarkSpyro               (  28u, Game.SpyrosAdventure, CharacterType.Character     ),
    Hex                     (  29u, Game.SpyrosAdventure, CharacterType.Character     ),
    ChopChop                (  30u, Game.SpyrosAdventure, CharacterType.Character     ),
    GhostRoaster            (  31u, Game.SpyrosAdventure, CharacterType.Character     ),
    Cynder                  (  32u, Game.SpyrosAdventure, CharacterType.Character     ),
    DebugMinionSSA          (  99u, Game.SpyrosAdventure, CharacterType.Character     , playability = Playability.Debug),
    JetVac                  ( 100u, Game.Giants         , CharacterType.Character     ),
    Swarm                   ( 101u, Game.Giants         , CharacterType.Character     ),
    Crusher                 ( 102u, Game.Giants         , CharacterType.Character     ),
    Flashwing               ( 103u, Game.Giants         , CharacterType.Character     ),
    HotHead                 ( 104u, Game.Giants         , CharacterType.Character     ),
    HotDog                  ( 105u, Game.Giants         , CharacterType.Character     ),
    Chill                   ( 106u, Game.Giants         , CharacterType.Character     ),
    Thumpback               ( 107u, Game.Giants         , CharacterType.Character     ),
    PopFizz                 ( 108u, Game.Giants         , CharacterType.Character     ),
    Ninjinni                ( 109u, Game.Giants         , CharacterType.Character     ),
    Bouncer                 ( 110u, Game.Giants         , CharacterType.Character     ),
    Sprocket                ( 111u, Game.Giants         , CharacterType.Character     ),
    TreeRex                 ( 112u, Game.Giants         , CharacterType.Character     ),
    Shroomboom              ( 113u, Game.Giants         , CharacterType.Character     ),
    EyeBrawl                ( 114u, Game.Giants         , CharacterType.Character     ),
    FrightRider             ( 115u, Game.Giants         , CharacterType.Character     ),
    Anvil                   ( 200u, Game.SpyrosAdventure, CharacterType.Item          ),
    SecretStash             ( 201u, Game.SpyrosAdventure, CharacterType.Item          ),
    Regeneration            ( 202u, Game.SpyrosAdventure, CharacterType.Item          ),
    CrossedSwords           ( 203u, Game.SpyrosAdventure, CharacterType.Item          ),
    Hourglass               ( 204u, Game.SpyrosAdventure, CharacterType.Item          ),
    Shield                  ( 205u, Game.SpyrosAdventure, CharacterType.Item          ),
    SpeedBoots              ( 206u, Game.SpyrosAdventure, CharacterType.Item          ),
    Sparx                   ( 207u, Game.SpyrosAdventure, CharacterType.Item          ),
    Cannon                  ( 208u, Game.Giants         , CharacterType.Item          ),
    Catapult                ( 209u, Game.Giants         , CharacterType.Item          ),
    MagicTrap               ( 210u, Game.TrapTeam       , CharacterType.Trap          ),
    WaterTrap               ( 211u, Game.TrapTeam       , CharacterType.Trap          ),
    AirTrap                 ( 212u, Game.TrapTeam       , CharacterType.Trap          ),
    DeathTrap               ( 213u, Game.TrapTeam       , CharacterType.Trap          ),
    TechTrap                ( 214u, Game.TrapTeam       , CharacterType.Trap          ),
    FireTrap                ( 215u, Game.TrapTeam       , CharacterType.Trap          ),
    EarthTrap               ( 216u, Game.TrapTeam       , CharacterType.Trap          ),
    LifeTrap                ( 217u, Game.TrapTeam       , CharacterType.Trap          ),
    DarkTrap                ( 218u, Game.TrapTeam       , CharacterType.Trap          ),
    LightTrap               ( 219u, Game.TrapTeam       , CharacterType.Trap          ),
    KaosTrap                ( 220u, Game.TrapTeam       , CharacterType.Trap          ),
    HandOfFate              ( 230u, Game.TrapTeam       , CharacterType.Item          ),
    PiggyBank               ( 231u, Game.TrapTeam       , CharacterType.Item          ),
    RocketRam               ( 232u, Game.TrapTeam       , CharacterType.Item          ),
    TikiSpeaky              ( 233u, Game.TrapTeam       , CharacterType.Item          ),
    Dragon                  ( 300u, Game.SpyrosAdventure, CharacterType.Expansion     ),
    Ice                     ( 301u, Game.SpyrosAdventure, CharacterType.Expansion     ),
    Pirate                  ( 302u, Game.SpyrosAdventure, CharacterType.Expansion     ),
    Undead                  ( 303u, Game.SpyrosAdventure, CharacterType.Expansion     ),
    PVPUnlock               ( 304u, Game.SpyrosAdventure, CharacterType.Expansion     ),
    MirrorOfMystery         ( 305u, Game.TrapTeam       , CharacterType.Expansion     ),
    NightmareExpress        ( 306u, Game.TrapTeam       , CharacterType.Expansion     ),
    SunscraperSpire         ( 307u, Game.TrapTeam       , CharacterType.Expansion     ),
    MidnightMuseum          ( 308u, Game.TrapTeam       , CharacterType.Expansion     ),
    BashLegendary           ( 404u, Game.SpyrosAdventure, CharacterType.Legendary     ),
    SpyroLegendary          ( 416u, Game.SpyrosAdventure, CharacterType.Legendary     ),
    TriggerHappyLegendary   ( 419u, Game.SpyrosAdventure, CharacterType.Legendary     ),
    ChopChopLegendary       ( 430u, Game.SpyrosAdventure, CharacterType.Legendary     ),
    Gusto                   ( 450u, Game.TrapTeam       , CharacterType.Character     ),
    Thunderbolt             ( 451u, Game.TrapTeam       , CharacterType.Character     ),
    FlingKong               ( 452u, Game.TrapTeam       , CharacterType.Character     ),
    Blades                  ( 453u, Game.TrapTeam       , CharacterType.Character     ),
    Wallop                  ( 454u, Game.TrapTeam       , CharacterType.Character     ),
    HeadRush                ( 455u, Game.TrapTeam       , CharacterType.Character     ),
    FistBump                ( 456u, Game.TrapTeam       , CharacterType.Character     ),
    RockyRoll               ( 457u, Game.TrapTeam       , CharacterType.Character     ),
    WildFire                ( 458u, Game.TrapTeam       , CharacterType.Character     ),
    KaBoom                  ( 459u, Game.TrapTeam       , CharacterType.Character     ),
    TrailBlazer             ( 460u, Game.TrapTeam       , CharacterType.Character     ),
    Torch                   ( 461u, Game.TrapTeam       , CharacterType.Character     ),
    SnapShot                ( 462u, Game.TrapTeam       , CharacterType.Character     ),
    LobStar                 ( 463u, Game.TrapTeam       , CharacterType.Character     ),
    FlipWreck               ( 464u, Game.TrapTeam       , CharacterType.Character     ),
    Echo                    ( 465u, Game.TrapTeam       , CharacterType.Character     ),
    Blastermind             ( 466u, Game.TrapTeam       , CharacterType.Character     ),
    Enigma                  ( 467u, Game.TrapTeam       , CharacterType.Character     ),
    DejaVu                  ( 468u, Game.TrapTeam       , CharacterType.Character     ),
    CobraCadabra            ( 469u, Game.TrapTeam       , CharacterType.Character     ),
    Jawbreaker              ( 470u, Game.TrapTeam       , CharacterType.Character     ),
    Gearshift               ( 471u, Game.TrapTeam       , CharacterType.Character     ),
    Chopper                 ( 472u, Game.TrapTeam       , CharacterType.Character     ),
    TreadHead               ( 473u, Game.TrapTeam       , CharacterType.Character     ),
    Bushwhack               ( 474u, Game.TrapTeam       , CharacterType.Character     ),
    TuffLuck                ( 475u, Game.TrapTeam       , CharacterType.Character     ),
    FoodFight               ( 476u, Game.TrapTeam       , CharacterType.Character     ),
    HighFive                ( 477u, Game.TrapTeam       , CharacterType.Character     ),
    KryptKing               ( 478u, Game.TrapTeam       , CharacterType.Character     ),
    ShortCut                ( 479u, Game.TrapTeam       , CharacterType.Character     ),
    BatSpin                 ( 480u, Game.TrapTeam       , CharacterType.Character     ),
    FunnyBone               ( 481u, Game.TrapTeam       , CharacterType.Character     ),
    KnightLight             ( 482u, Game.TrapTeam       , CharacterType.Character     ),
    SpotLight               ( 483u, Game.TrapTeam       , CharacterType.Character     ),
    KnightMare              ( 484u, Game.TrapTeam       , CharacterType.Character     ),
    Blackout                ( 485u, Game.TrapTeam       , CharacterType.Character     ),
    Bop                     ( 502u, Game.TrapTeam       , CharacterType.Mini          ),
    Spry                    ( 503u, Game.TrapTeam       , CharacterType.Mini          ),
    Hijinx                  ( 504u, Game.TrapTeam       , CharacterType.Mini          ),
    Terrabite               ( 505u, Game.SpyrosAdventure, CharacterType.Sidekick      ),
    Breeze                  ( 506u, Game.TrapTeam       , CharacterType.Mini          ),
    Weerupter               ( 507u, Game.TrapTeam       , CharacterType.Mini          ),
    PetVac                  ( 508u, Game.TrapTeam       , CharacterType.Mini          ),
    SmallFry                ( 509u, Game.TrapTeam       , CharacterType.Mini          ),
    Drobit                  ( 510u, Game.TrapTeam       , CharacterType.Mini          ),
    GillRunt                ( 514u, Game.SpyrosAdventure, CharacterType.Sidekick      ),
    TriggerSnappy           ( 519u, Game.SpyrosAdventure, CharacterType.Sidekick      ),
    WhisperElf              ( 526u, Game.SpyrosAdventure, CharacterType.Sidekick      ),
    Barkely                 ( 540u, Game.Giants         , CharacterType.Sidekick      ),
    Thumpling               ( 541u, Game.Giants         , CharacterType.Sidekick      ),
    MiniJini                ( 542u, Game.Giants         , CharacterType.Sidekick      ),
    EyeSmall                ( 543u, Game.Giants         , CharacterType.Sidekick      ),
    DebugMinionSG           ( 999u, Game.Giants         , CharacterType.Character     , playability = Playability.Debug),
    AviatorLegs             (1000u, Game.SwapForce      , CharacterType.SwapLegs      ),
    StormBirdLegs           (1001u, Game.SwapForce      , CharacterType.SwapLegs      ),
    MinerLegs               (1002u, Game.SwapForce      , CharacterType.SwapLegs      ),
    StatueLegs              (1003u, Game.SwapForce      , CharacterType.SwapLegs      ),
    FireKnightLegs          (1004u, Game.SwapForce      , CharacterType.SwapLegs      ),
    FireworksLegs           (1005u, Game.SwapForce      , CharacterType.SwapLegs      ),
    NinjaLegs               (1006u, Game.SwapForce      , CharacterType.SwapLegs      ),
    GorillaLegs             (1007u, Game.SwapForce      , CharacterType.SwapLegs      ),
    FortuneLegs             (1008u, Game.SwapForce      , CharacterType.SwapLegs      ),
    PantherLegs             (1009u, Game.SwapForce      , CharacterType.SwapLegs      ),
    MagnetLegs              (1010u, Game.SwapForce      , CharacterType.SwapLegs      ),
    SpyderLegs              (1011u, Game.SwapForce      , CharacterType.SwapLegs      ),
    VampireLegs             (1012u, Game.SwapForce      , CharacterType.SwapLegs      ),
    CowboyLegs              (1013u, Game.SwapForce      , CharacterType.SwapLegs      ),
    FreezeLegs              (1014u, Game.SwapForce      , CharacterType.SwapLegs      ),
    PirateLegs              (1015u, Game.SwapForce      , CharacterType.SwapLegs      ),
    TemplateSwapLegs        (1999u, Game.SwapForce      , CharacterType.SwapLegs      , playability = Playability.Debug),
    AviatorBody             (2000u, Game.SwapForce      , CharacterType.SwapBody      ),
    StormBirdBody           (2001u, Game.SwapForce      , CharacterType.SwapBody      ),
    MinerBody               (2002u, Game.SwapForce      , CharacterType.SwapBody      ),
    StatueBody              (2003u, Game.SwapForce      , CharacterType.SwapBody      ),
    FireKnightBody          (2004u, Game.SwapForce      , CharacterType.SwapBody      ),
    FireworksBody           (2005u, Game.SwapForce      , CharacterType.SwapBody      ),
    NinjaBody               (2006u, Game.SwapForce      , CharacterType.SwapBody      ),
    GorillaBody             (2007u, Game.SwapForce      , CharacterType.SwapBody      ),
    FortuneBody             (2008u, Game.SwapForce      , CharacterType.SwapBody      ),
    PantherBody             (2009u, Game.SwapForce      , CharacterType.SwapBody      ),
    MagnetBody              (2010u, Game.SwapForce      , CharacterType.SwapBody      ),
    SpyderBody              (2011u, Game.SwapForce      , CharacterType.SwapBody      ),
    VampireBody             (2012u, Game.SwapForce      , CharacterType.SwapBody      ),
    CowboyBody              (2013u, Game.SwapForce      , CharacterType.SwapBody      ),
    FreezeBody              (2014u, Game.SwapForce      , CharacterType.SwapBody      ),
    PirateBody              (2015u, Game.SwapForce      , CharacterType.SwapBody      ),
    TemplateSwapBody        (2999u, Game.SwapForce      , CharacterType.SwapBody      , playability = Playability.Debug),
    CatGryphon              (3000u, Game.SwapForce      , CharacterType.Character     ),
    PuffDragon              (3001u, Game.SwapForce      , CharacterType.Character     ),
    LockJaw                 (3002u, Game.SwapForce      , CharacterType.Character     ),
    Scorpion                (3003u, Game.SwapForce      , CharacterType.Character     ),
    Fyno                    (3004u, Game.SwapForce      , CharacterType.Character     ),
    SunGirl                 (3005u, Game.SwapForce      , CharacterType.Character     ),
    BeeTree                 (3006u, Game.SwapForce      , CharacterType.Character     ),
    Shaman                  (3007u, Game.SwapForce      , CharacterType.Character     ),
    DuneBug                 (3008u, Game.SwapForce      , CharacterType.Character     ),
    FanGirl                 (3009u, Game.SwapForce      , CharacterType.Character     ),
    DaBomb                  (3010u, Game.SwapForce      , CharacterType.Character     ),
    WindUp                  (3011u, Game.SwapForce      , CharacterType.Character     ),
    TopsyDerby              (3012u, Game.SwapForce      , CharacterType.Character     ),
    Reaper                  (3013u, Game.SwapForce      , CharacterType.Character     ),
    Swordfish               (3014u, Game.SwapForce      , CharacterType.Character     ),
    EelGirl                 (3015u, Game.SwapForce      , CharacterType.Character     ),
    Hammer                  (3200u, Game.SwapForce      , CharacterType.Item          ),
    Diamonds                (3201u, Game.SwapForce      , CharacterType.Item          ),
    GoldenSheep             (3202u, Game.SwapForce      , CharacterType.Item          ),
    Gramophone              (3203u, Game.SwapForce      , CharacterType.Item          ),
    HatPromo                (3204u, Game.SwapForce      , CharacterType.Item          ),
    AirJet                  (3220u, Game.SuperChargers  , CharacterType.Vehicle       ),
    UndeadBuggy             (3221u, Game.SuperChargers  , CharacterType.Vehicle       ),
    WaterFishSub            (3222u, Game.SuperChargers  , CharacterType.Vehicle       ),
    FireBike                (3223u, Game.SuperChargers  , CharacterType.Vehicle       ),
    FireCar                 (3224u, Game.SuperChargers  , CharacterType.Vehicle       ),
    EarthTank               (3225u, Game.SuperChargers  , CharacterType.Vehicle       ),
    EarthTruck              (3226u, Game.SuperChargers  , CharacterType.Vehicle       ),
    UndeadCar               (3227u, Game.SuperChargers  , CharacterType.Vehicle       ),
    LifeCopter              (3228u, Game.SuperChargers  , CharacterType.Vehicle       ),
    WaterTorpedoSub         (3231u, Game.SuperChargers  , CharacterType.Vehicle       ),
    AirPlane                (3232u, Game.SuperChargers  , CharacterType.Vehicle       ),
    ClownPlane              (3233u, Game.SuperChargers  , CharacterType.Vehicle       ),
    TechBike                (3234u, Game.SuperChargers  , CharacterType.Vehicle       ),
    TechTruck               (3235u, Game.SuperChargers  , CharacterType.Vehicle       ),
    LightPlane              (3236u, Game.SuperChargers  , CharacterType.Vehicle       ),
    DarkMantaSub            (3237u, Game.SuperChargers  , CharacterType.Vehicle       ),
    MagicSub                (3238u, Game.SuperChargers  , CharacterType.Vehicle       ),
    MagicFloat              (3239u, Game.SuperChargers  , CharacterType.Vehicle       ),
    DKCart                  (3240u, Game.SuperChargers  , CharacterType.Vehicle       ),
    LifePlane               (3241u, Game.SuperChargers  , CharacterType.Vehicle       ),
    SheepWreckIsland        (3300u, Game.SwapForce      , CharacterType.Expansion     ),
    ClockTower              (3301u, Game.SwapForce      , CharacterType.Expansion     ),
    BattleArena1            (3302u, Game.SwapForce      , CharacterType.Expansion     ),
    BattleArena2            (3303u, Game.SwapForce      , CharacterType.Expansion     ),
    SoulJam                 (3400u, Game.SuperChargers  , CharacterType.Character     ),
    Lightbulb               (3401u, Game.SuperChargers  , CharacterType.Character     ),
    InkGirl                 (3402u, Game.SuperChargers  , CharacterType.Character     ),
    Peacock                 (3406u, Game.SuperChargers  , CharacterType.Character     ),
    Koala                   (3411u, Game.SuperChargers  , CharacterType.Character     ),
    Nitro                   (3412u, Game.SuperChargers  , CharacterType.Character     ),
    DriverJetVac            (3413u, Game.SuperChargers  , CharacterType.Character     ),
    DriverTriggerHappy      (3414u, Game.SuperChargers  , CharacterType.Character     ),
    DriverStealthElf        (3415u, Game.SuperChargers  , CharacterType.Character     ),
    DriverTerrafin          (3416u, Game.SuperChargers  , CharacterType.Character     ),
    DriverRollerBrawl       (3417u, Game.SuperChargers  , CharacterType.Character     ),
    DriverPopFizz           (3420u, Game.SuperChargers  , CharacterType.Character     ),
    DriverEruptor           (3421u, Game.SuperChargers  , CharacterType.Character     ),
    DriverGillGrunt         (3422u, Game.SuperChargers  , CharacterType.Character     ),
    DonkeyKong              (3423u, Game.SuperChargers  , CharacterType.Character     ),
    Bowser                  (3424u, Game.SuperChargers  , CharacterType.Character     ),
    AirLock                 (3425u, Game.SuperChargers  , CharacterType.Character     ),
    LightDriver             (3426u, Game.SuperChargers  , CharacterType.Character     ),
    DarkDriver              (3427u, Game.SuperChargers  , CharacterType.Character     ),
    LifeBug                 (3428u, Game.SuperChargers  , CharacterType.Character     ),
    ChefPepperJackDriver    (3440u, Game.SuperChargers  , CharacterType.VillainDriver ),
    StratosDriver           (3441u, Game.SuperChargers  , CharacterType.VillainDriver ),
    CluckDriver             (3442u, Game.SuperChargers  , CharacterType.VillainDriver ),
    WolfgangDriver          (3443u, Game.SuperChargers  , CharacterType.VillainDriver ),
    ThreatPackDriver        (3444u, Game.SuperChargers  , CharacterType.VillainDriver , playability = Playability.NotPlayable),
    HoodSickleDriver        (3445u, Game.SuperChargers  , CharacterType.VillainDriver , playability = Playability.NotPlayable),
    BadJujuDriver           (3446u, Game.SuperChargers  , CharacterType.VillainDriver , playability = Playability.NotPlayable),
    GlumshanksDriver        (3450u, Game.SuperChargers  , CharacterType.VillainDriver ),
    KaosAgentDriver         (3451u, Game.SuperChargers  , CharacterType.VillainDriver ),
    MoneyboneDriver         (3452u, Game.SuperChargers  , CharacterType.VillainDriver ),
    ChompyMageDriver        (3453u, Game.SuperChargers  , CharacterType.VillainDriver ),
    KrankcaseDriver         (3454u, Game.SuperChargers  , CharacterType.VillainDriver , playability = Playability.NotPlayable),
    PainYattaDriver         (3455u, Game.SuperChargers  , CharacterType.VillainDriver , playability = Playability.NotPlayable),
    BrocoliGuyDriver        (3456u, Game.SuperChargers  , CharacterType.VillainDriver , playability = Playability.NotPlayable),
    MesmeraldaDriver        (3460u, Game.SuperChargers  , CharacterType.VillainDriver ),
    FreightBeardDriver      (3461u, Game.SuperChargers  , CharacterType.VillainDriver ),
    GoldenQueenDriver       (3462u, Game.SuperChargers  , CharacterType.VillainDriver ),
    SpellpunkBossDriver     (3463u, Game.SuperChargers  , CharacterType.VillainDriver ),
    ChillBillDriver         (3464u, Game.SuperChargers  , CharacterType.VillainDriver , playability = Playability.NotPlayable),
    GulperDriver            (3465u, Game.SuperChargers  , CharacterType.VillainDriver , playability = Playability.NotPlayable),
    NoodlesDriver           (3466u, Game.SuperChargers  , CharacterType.VillainDriver , playability = Playability.NotPlayable),
    KaosDriver              (3467u, Game.SuperChargers  , CharacterType.VillainDriver ),
    ChefPepperJackVehicle   (3470u, Game.SuperChargers  , CharacterType.VillainVehicle),
    StratosVehicle          (3471u, Game.SuperChargers  , CharacterType.VillainVehicle),
    CluckVehicle            (3472u, Game.SuperChargers  , CharacterType.VillainVehicle),
    WolfgangVehicle         (3473u, Game.SuperChargers  , CharacterType.VillainVehicle),
    ThreatPackVehicle       (3474u, Game.SuperChargers  , CharacterType.VillainVehicle, playability = Playability.NotPlayable),
    HoodSickleVehicle       (3475u, Game.SuperChargers  , CharacterType.VillainVehicle, playability = Playability.NotPlayable),
    BadJujuVehicle          (3476u, Game.SuperChargers  , CharacterType.VillainVehicle, playability = Playability.NotPlayable),
    GlumshanksVehicle       (3480u, Game.SuperChargers  , CharacterType.VillainVehicle),
    KaosAgentVehicle        (3481u, Game.SuperChargers  , CharacterType.VillainVehicle),
    MoneyboneVehicle        (3482u, Game.SuperChargers  , CharacterType.VillainVehicle),
    ChompyMageVehicle       (3483u, Game.SuperChargers  , CharacterType.VillainVehicle),
    KrankcaseVehicle        (3484u, Game.SuperChargers  , CharacterType.VillainVehicle, playability = Playability.NotPlayable),
    PainYattaVehicle        (3485u, Game.SuperChargers  , CharacterType.VillainVehicle, playability = Playability.NotPlayable),
    BrocoliGuyVehicle       (3486u, Game.SuperChargers  , CharacterType.VillainVehicle, playability = Playability.NotPlayable),
    MesmeraldaVehicle       (3490u, Game.SuperChargers  , CharacterType.VillainVehicle),
    FreightBeardVehicle     (3491u, Game.SuperChargers  , CharacterType.VillainVehicle),
    GoldenQueenVehicle      (3492u, Game.SuperChargers  , CharacterType.VillainVehicle),
    SpellpunkBossVehicle    (3493u, Game.SuperChargers  , CharacterType.VillainVehicle),
    ChillBillVehicle        (3494u, Game.SuperChargers  , CharacterType.VillainVehicle, playability = Playability.NotPlayable),
    GulperVehicle           (3495u, Game.SuperChargers  , CharacterType.VillainVehicle, playability = Playability.NotPlayable),
    NoodlesVehicle          (3496u, Game.SuperChargers  , CharacterType.VillainVehicle, playability = Playability.NotPlayable),
    KaosVehicle             (3497u, Game.SuperChargers  , CharacterType.VillainVehicle),
    SkyTrophy               (3500u, Game.SuperChargers  , CharacterType.Trophy        ),
    LandTrophy              (3501u, Game.SuperChargers  , CharacterType.Trophy        ),
    SeaTrophy               (3502u, Game.SuperChargers  , CharacterType.Trophy        ),
    KaosTrophy              (3503u, Game.SuperChargers  , CharacterType.Trophy        ),
    NightFall_Error         (3527u, Game.SuperChargers  , CharacterType.Character     , playability = Playability.Debug),
    TemplateCharacterSSF    (3999u, Game.SwapForce      , CharacterType.Character     , playability = Playability.Debug),
    Fusion                  (4500u, Game.Imaginators    , CharacterType.Character     ),
    Synergy                 (4501u, Game.Imaginators    , CharacterType.Character     ),
    Unity                   (4502u, Game.Imaginators    , CharacterType.Character     ),
    BlueFalcon              (4503u, Game.Imaginators    , CharacterType.Character     ),
    TemplateVehicle         (4999u, Game.SuperChargers  , CharacterType.Vehicle       , playability = Playability.Debug),
    TemplateVehicleLand     (5999u, Game.SuperChargers  , CharacterType.Vehicle       , playability = Playability.Debug),
    TemplateVehicleAir      (6999u, Game.SuperChargers  , CharacterType.Vehicle       , playability = Playability.Debug),
    TemplateVehicleSea      (7999u, Game.SuperChargers  , CharacterType.Vehicle       , playability = Playability.Debug),
}