package edu.jorbonism.nfclanders.enums

enum class Deco(val ord: UByte, val label: String) {
    Normal              ( 0u, "Normal"            ),
    Repose1             ( 1u, "Repose 1"          ),
    Alternate           ( 2u, "Alternate Deco"    ),
    Legendary           ( 3u, "Legendary"         ),
    Event               ( 4u, "Event"             ),
    Repose2             ( 5u, "Repose 2"          ),
    LightDirect         ( 6u, "Light Direct"      ),
    LightStored         ( 7u, "Light Stored"      ),
    LightEnhanced       ( 8u, "Light Enhanced"    ),
    Repose3             ( 9u, "Repose 3"          ),
    Repose4             (10u, "Repose 4"          ),
    Repose5             (11u, "Repose 5"          ),
    Valentines          (12u, "Valentine's"       ),
    Easter              (13u, "Easter"            ),
    Winter              (14u, "Winter"            ),
    Virtual             (15u, "Virtual"           ),
    Premium             (16u, "Premium"           ),
    GlowDark            (17u, "Glow in the Dark"  ),
    StoneStatue         (18u, "Stone Statue"      ),
    GlitterSpectrum     (19u, "Glitter Spectrum"  ),
    TreasureHunt2012    (20u, "Treasure Hunt 2012"),
    Halloween           (21u, "Halloween"         ),
    TreasureHunt2013    (22u, "Treasure Hunt 2013"),
    ColorShift          (23u, "Color Shift"       ),
    WiiU                (24u, "Wii U"             ),
    BestBuy             (25u, "Best Buy"          ),
    FritoLay            (26u, "Frito Lay"         ),
    Deco27              (27u, "Deco 27"           ),
    Deco28              (28u, "Deco 28"           ),
    TreasureHunt2014    (29u, "Treasure Hunt 2014"),
    TreasureHunt2015    (30u, "Treasure Hunt 2015"),
    Mobile              (31u, "Mobile"            ),
}
