package edu.jorbonism.nfclanders.enums

import android.util.Log

enum class Hat(val ord: UShort, val version: Int, val label: String) {
    None                (  0u, 0, ""                                 ),
    Army                (  1u, 0, "Combat Hat"                       ),
    French              (  2u, 0, "Napoleon Hat"                     ),
    Goggles             (  3u, 0, "Spy Gear"                         ),
    Mining              (  4u, 0, "Miner Hat"                        ),
    Officer             (  5u, 0, "General's Hat"                    ),
    Pirate              (  6u, 0, "Pirate Hat"                       ),
    Propeller           (  7u, 0, "Propeller Cap"                    ),
    Raccoon             (  8u, 0, "Coonskin Cap"                     ),
    Straw               (  9u, 0, "Straw Hat"                        ),
    Sunday              ( 10u, 0, "Fancy Hat (Monday)"               ),
    Tophat              ( 11u, 0, "Top Hat"                          ),
    Viking              ( 12u, 0, "Viking Helmet"                    ),
    WorldWarI           ( 13u, 0, "Spiked Hat"                       ),
    Anvil               ( 14u, 0, "Anvil Hat"                        ),
    Beret               ( 15u, 0, "Beret"                            ),
    BirthdayCap         ( 16u, 0, "Birthday Hat"                     ),
    Bonehead            ( 17u, 0, "Bone Head"                        ),
    Bowler              ( 18u, 0, "Bowler Hat"                       ),
    Bunny               ( 19u, 0, "Wabbit Ears"                      ),
    Carmen              ( 20u, 0, "Tropical Turban"                  ),
    Chef                ( 21u, 0, "Chef Hat"                         ),
    Cowboy              ( 22u, 0, "Cowboy Hat"                       ),
    CrazyHair           ( 23u, 0, "Rocker Hair"                      ),
    Crown               ( 24u, 0, "Royal Crown"                      ),
    DevilHorns          ( 25u, 0, "Lil' Devil"                       ),
    Eyeball             ( 26u, 0, "Eye Hat"                          ),
    Fez                 ( 27u, 0, "Fez"                              ),
    Halo                ( 28u, 0, "Crown of Light"                   ),
    Jester              ( 29u, 0, "Jester Hat"                       ),
    Mercury             ( 30u, 0, "Winged Hat"                       ),
    Moose               ( 31u, 0, "Moose Hat"                        ),
    Plunger             ( 32u, 0, "Plunger Head"                     ),
    Pot                 ( 33u, 0, "Pan Hat"                          ),
    Rocket              ( 34u, 0, "Rocket Hat"                       ),
    Santa               ( 35u, 0, "Santa Hat"                        ),
    Tiki                ( 36u, 0, "Tiki Hat"                         ),
    Trojan              ( 37u, 0, "Trojan Helmet"                    ),
    Unicorn             ( 38u, 0, "Unicorn Hat"                      ),
    Wizard              ( 39u, 0, "Wizard Hat (Spyro's Adventure)"   ),
    Pumpkin             ( 40u, 0, "Pumpkin Hat"                      ),
    PirateBandana       ( 41u, 0, "Pirate Doo Rag"                   ),
    Cossack             ( 42u, 0, "Cossack Hat"                      ),
    FlowerPot           ( 43u, 0, "Flower Hat"                       ),
    Balloon             ( 44u, 0, "Balloon Hat"                      ),
    BirthdayCake        ( 45u, 0, "Happy Birthday!"                  ),
    VintageBaseballCap  ( 46u, 1, "Vintage Baseball Cap"             ),
    Hat47               ( 47u, 1, "Hat 47"                           ),
    BowlingPin          ( 48u, 1, "Bowling Pin Hat"                  ),
    Officer2            ( 49u, 1, "Officer Cap"                      ),
    FirefighterHelmet   ( 50u, 1, "Firefighter Helmet"               ),
    Graduation          ( 51u, 1, "Graduation Hat"                   ),
    Lampshade           ( 52u, 1, "Lampshade Hat"                    ),
    Mariachi            ( 53u, 1, "Mariachi Hat"                     ),
    Hat54               ( 54u, 1, "Hat 54"                           ),
    PaperFastFood       ( 55u, 1, "Paper Fast Food Hat"              ),
    Pilgrim             ( 56u, 1, "Pilgrim Hat"                      ),
    PoliceSiren         ( 57u, 1, "Police Siren Hat"                 ),
    PurpleFedora        ( 58u, 1, "Purple Fedora"                    ),
    Archer              ( 59u, 1, "Archer Hat"                       ),
    Hat60               ( 60u, 1, "Hat 60"                           ),
    Safari              ( 61u, 1, "Safari Hat"                       ),
    Sailor              ( 62u, 1, "Sailor Hat"                       ),
    Hat63               ( 63u, 1, "Hat 63"                           ),
    Dancer              ( 64u, 1, "Dancer Hat"                       ),
    TrafficCone         ( 65u, 1, "Traffic Cone Hat"                 ),
    Turban              ( 66u, 1, "Turban"                           ),
    BattleHelmet        ( 67u, 1, "Battle Helmet"                    ),
    BottleCap           ( 68u, 1, "Bottle Cap Hat"                   ),
    Hat69               ( 69u, 1, "Hat 69"                           ),
    Carrot              ( 70u, 1, "Carrot Hat"                       ),
    Hat71               ( 71u, 1, "Hat 71"                           ),
    Elf                 ( 72u, 1, "Elf Hat"                          ),
    Fishing             ( 73u, 1, "Fishing Hat"                      ),
    Future              ( 74u, 1, "Future Hat"                       ),
    Nefertiti           ( 75u, 1, "Nefertiti"                        ),
    Hat76               ( 76u, 1, "Hat 76"                           ),
    Pants               ( 77u, 1, "Pants Hat"                        ),
    Princess            ( 78u, 1, "Princess Hat"                     ),
    ToySoldier          ( 79u, 1, "Toy Soldier Hat"                  ),
    Trucker             ( 80u, 1, "Trucker Hat"                      ),
    Umbrella            ( 81u, 1, "Umbrella Hat"                     ),
    Showtime            ( 82u, 1, "Showtime Hat"                     ),
    Caesar              ( 83u, 1, "Caesar Hat"                       ),
    FlowerFairy         ( 84u, 1, "Flower Fairy Hat"                 ),
    Funnel              ( 85u, 1, "Funnel Hat"                       ),
    Scrumshanks         ( 86u, 1, "Scrumshanks Hat"                  ),
    Biter               ( 87u, 1, "Biter Hat"                        ),
    Atom                ( 88u, 1, "Atom Hat"                         ),
    Sombrero            ( 89u, 1, "Sombrero"                         ),
    Rasta               ( 90u, 1, "Rasta Hat"                        ),
    Kufi                ( 91u, 1, "Kufi Hat"                         ),
    KnightHelm          ( 92u, 1, "Knight Helm"                      ),
    DanglingCarrot      ( 93u, 1, "Dangling Carrot Hat"              ),
    BronzeTopHat        ( 94u, 1, "Bronze Top Hat"                   ),
    SilverTopHat        ( 95u, 1, "Silver Top Hat"                   ),
    GoldTopHat          ( 96u, 1, "Gold Top Hat"                     ),
    Rain                ( 97u, 2, "Rain Hat"                         ),
    SnorkelingMask      ( 98u, 2, "The Outsider"                     ),
    Greeble             ( 99u, 2, "Greeble Hat"                      ),
    Volcano             (100u, 2, "Volcano Hat"                      ),
    Boater              (101u, 2, "Boater Hat"                       ),
    Stone               (102u, 2, "Stone Hat"                        ),
    Stovepipe           (103u, 2, "Stovepipe Hat"                    ),
    Boonie              (104u, 2, "Boonie Hat"                       ),
    Sawblade            (105u, 2, "Sawblade Hat"                     ),
    SunBonnet           (106u, 2, "Zombeanie Hat"                    ),
    Gaucho              (107u, 2, "Gaucho Hat"                       ),
    Roundlet            (108u, 2, "Roundlet Hat"                     ),
    Capuchon            (109u, 2, "Capuchon"                         ),
    Tricorn             (110u, 2, "Tricorn Hat"                      ),
    FeatheredHeaddress  (111u, 2, "Feathered Headdress (Peacock Hat)"),
    BearskinCap         (112u, 2, "Bearskin Cap"                     ),
    Fishbone            (113u, 2, "Fishbone Hat"                     ),
    SkiCap              (114u, 2, "Ski Cap"                          ),
    CrownOfFrost        (115u, 2, "Crown of Frost"                   ),
    FourWinds           (116u, 2, "Four Winds Hat"                   ),
    Beacon              (117u, 2, "Beacon Hat"                       ),
    FlowerGarland       (118u, 2, "Flower Garland"                   ),
    TreeBranch          (119u, 2, "Tree Branch"                      ),
    AviatorsCap         (120u, 2, "Aviator's Cap"                    ),
    Asteroid            (121u, 2, "Asteroid Hat"                     ),
    Crystal             (122u, 2, "Crystal Hat"                      ),
    CreepyHelm          (123u, 2, "Creepy Helm"                      ),
    FancyRibbon         (124u, 2, "Fancy Ribbon"                     ),
    DeelyBoppers        (125u, 2, "Deely Boppers"                    ),
    BeanieCap           (126u, 2, "Beanie"                           ),
    Leprechaun          (127u, 2, "Leprechaun Hat"                   ),
    Shark               (128u, 2, "Shark Hat (Sharkfin Hat)"         ),
    LifePreserver       (129u, 2, "Life Preserver Hat"               ),
    GlitteringTiara     (130u, 2, "Glittering Tiara"                 ),
    GreatHelm           (131u, 2, "Great Helm"                       ),
    SpaceHelmet         (132u, 2, "Space Helmet"                     ),
    UFO                 (133u, 2, "UFO Hat"                          ),
    WhirlwindDiadem     (134u, 2, "Whirlwind Diadem"                 ),
    ObsidianHelm        (135u, 2, "Obsidian Helm"                    ),
    Lilypad             (136u, 2, "Lilypad Hat"                      ),
    CrownOfFlames       (137u, 2, "Crown of Flames"                  ),
    RunicHeadband       (138u, 2, "Runic Headband"                   ),
    Clockwork           (139u, 2, "Clockwork Hat"                    ),
    Cactus              (140u, 2, "Cactus Hat"                       ),
    SkullHelm           (141u, 2, "Skullhelm (Skyll)"                ),
    Gloop               (142u, 2, "Gloop Hat"                        ),
    Puma                (143u, 2, "Puma Hat"                         ),
    Elephant            (144u, 2, "Elephant Hat"                     ),
    TigerSkin           (145u, 2, "Tiger Skin Cap"                   ),
    TeethTop            (146u, 2, "Teeth Top Hat"                    ),
    Turkey              (147u, 2, "Turkey Hat"                       ),
    Afro                (148u, 2, "Eyefro"                           ),
    BaconBandana        (149u, 2, "Bacon Bandana"                    ),
    AwesomeHat          (150u, 2, "Awesome Hat"                      ),
    CardShark           (151u, 2, "Card Shark Hat"                   ),
    EasterTriggerHappy  (152u, 2, "Springtime Hat"                   ),
    HolidayBumbleBlast  (153u, 2, "Jolly Hat"                        ),
    SoccerCountdown     (154u, 2, "Kickoff Hat"                      ),
    Beetle              (155u, 2, "Beetle Hat"                       ),
    Brain               (156u, 2, "Brain Hat"                        ),
    Brainiac            (157u, 2, "Brainiac Hat"                     ),
    Bucket              (158u, 2, "Bucket Hat"                       ),
    Cactus02            (159u, 2, "Desert Crown"                     ),
    Fan                 (160u, 2, "Ceiling Fan Hat"                  ),
    Chinese             (161u, 2, "Imperial Hat"                     ),
    Clown               (162u, 2, "Clown Classic Hat"                ),
    ClownBowler         (163u, 2, "Clown Bowler Hat"                 ),
    Colander            (164u, 2, "Colander Hat"                     ),
    Kepi                (165u, 2, "Kepi Hat"                         ),
    Cornucopia          (166u, 2, "Cornucopia Hat"                   ),
    Cubano              (167u, 2, "Cubano Hat"                       ),
    Cycling             (168u, 2, "Cycling Hat"                      ),
    DaisyCrown          (169u, 2, "Daisy Crown"                      ),
    Skull               (170u, 2, "Dragon Skull"                     ),
    DundeeSlouch        (171u, 2, "Outback Hat"                      ),
    ElfMini             (172u, 2, "Lil' Elf Hat"                     ),
    Castro              (173u, 2, "Generalissimo"                    ),
    Garrison            (174u, 2, "Garrison Hat"                     ),
    Gondolier           (175u, 2, "Gondolier Hat"                    ),
    Hunting             (176u, 2, "Hunting Hat"                      ),
    Juicer              (177u, 2, "Juicer Hat"                       ),
    Kokoshnik           (178u, 2, "Kokoshnik"                        ),
    Medic               (179u, 2, "Medic Hat"                        ),
    Melon               (180u, 2, "Melon Hat"                        ),
    Mountie             (181u, 2, "Mountie Hat"                      ),
    Nurse               (182u, 2, "Nurse Hat"                        ),
    Palm                (183u, 2, "Palm Hat"                         ),
    Paperboy            (184u, 2, "Paperboy Hat"                     ),
    ParrotRoosting      (185u, 2, "Parrot Nest"                      ),
    Projector           (186u, 2, "Old-Time Movie Hat"               ),
    Pot02               (187u, 2, "Classic Pot Hat"                  ),
    Radar               (188u, 2, "Radar Hat"                        ),
    Tiara               (189u, 2, "Crazy Light Bulb Hat"             ),
    RubberGlove         (190u, 2, "Rubber Glove Hat"                 ),
    Rugby               (191u, 2, "Rugby Hat"                        ),
    SharkFin            (192u, 2, "Metal Fin Hat"                    ),
    Sherlock            (193u, 2, "Sleuth Hat"                       ),
    Shower              (194u, 2, "Shower Cap"                       ),
    Bobby               (195u, 2, "Bobby"                            ),
    Hedgehog            (196u, 2, "Hedgehog Hat"                     ),
    Steampunk           (197u, 2, "Steampunk Hat"                    ),
    Stewardess          (198u, 2, "Flight Attendant Hat"             ),
    SundayFancy         (199u, 2, "Monday Hat"                       ),
    Tibet               (200u, 2, "Sherpa Hat"                       ),
    Trash               (201u, 2, "Trash Lid"                        ),
    Turtle              (202u, 2, "Turtle Hat"                       ),
    UFO02               (203u, 2, "Extreme Viking Hat"               ),
    Vespa               (204u, 2, "Scooter Hat"                      ),
    Volcano02           (205u, 2, "Volcano Island Hat"               ),
    WaterBallet         (206u, 2, "Synchronized Swimming Cap"        ),
    WilliamTell         (207u, 2, "William Tell Hat"                 ),
    Zulu                (208u, 2, "Tribal Hat"                       ),
    RudeBoyChecker      (209u, 2, "Rude Boy Hat"                     ),
    PorkPieChecker      (210u, 2, "Pork Pie Hat"                     ),
    AlarmClock          (211u, 2, "Alarm Clock Hat"                  ),
    Armadillo           (212u, 2, "Batter Up Hat"                    ),
    BearTrap            (213u, 2, "Horns Be With You"                ),
    Croissant           (214u, 2, "Croissant Hat"                    ),
    WeatherVane         (215u, 2, "Weather Vane Hat"                 ),
    Rainbow             (216u, 2, "Rainbow Hat"                      ),
    EyeOfKaos           (217u, 2, "Eye of Kaos Hat"                  ),
    BatEars             (218u, 2, "Bat Hat"                          ),
    Lightbulb           (219u, 2, "Light Bulb"                       ),
    Fireflies           (220u, 2, "Firefly Jar"                      ),
    ShadowGhost         (221u, 2, "Shadow Ghost Hat"                 ),
    Lighthouse          (222u, 2, "Lighthouse Beacon Hat"            ),
    TinFoil             (223u, 2, "Tin Foil Hat"                     ),
    NightCap            (224u, 2, "Night Cap"                        ),
    Storm               (225u, 2, "Storm Hat"                        ),
    KnightmareGold      (226u, 2, "Gold Arkeyan Helm"                ),
    Duck                (227u, 2, "Toucan Hat"                       ),
    Pyramid             (228u, 2, "Pyramid Hat"                      ),
    Windmill            (229u, 2, "Miniature Skylands Hat"           ),
    Wizard02            (230u, 2, "Wizard Hat (Trap Team)"           ),
    Hat231              (231u, 2, "Hat 231"                          ),
    Confectioner        (232u, 2, "Candy Cane Hat"                   ),
    Eggshell            (233u, 2, "Eggshell Hat"                     ),
    Candle              (234u, 2, "Candle Hat"                       ),
    HelmDark            (235u, 2, "Dark Helm"                        ),
    Orbit               (236u, 2, "Planet Hat"                       ),
    Bellhop             (237u, 2, "Bellhop Hat"                      ),
    KnightmareBronze    (238u, 2, "Bronze Arkeyan Helm"              ),
    KnightmareSilver    (239u, 2, "Silver Arkeyan Helm"              ),
    Raver               (240u, 2, "Raver Hat"                        ),
    Shire               (241u, 2, "Shire Hat"                        ),
    Mongol              (242u, 2, "Mongol Hat"                       ),
    FishermanSlicker    (243u, 2, "Skipper Hat"                      ),
    MedievalBard        (244u, 2, "Medieval Bard Hat"                ),
    Wooden              (245u, 2, "Wooden Hat"                       ),
    Carnival            (246u, 2, "Carnival Hat"                     ),
    Coconut             (247u, 2, "Coconut Hat"                      ),
    Wilikin             (248u, 2, "Model Home Hat"                   ),
    Frostfest           (249u, 2, "Ice Cream Hat"                    ),
    Molekin             (250u, 2, "Molekin Mountain Hat"             ),
    Sheepwrecked        (251u, 2, "Sheepwrecked Hat"                 ),
    OldRuins            (252u, 2, "Core of Light Hat"                ),
    Oracle              (253u, 2, "Octavius Cloptimus Hat"           ),
    Hat254              (254u, 2, "Hat 254"                          ),
    Hat255              (255u, 2, "Hat 255"                          ),
    Hat256              (256u, 3, "Hat 256"                          ),
    Hat257              (257u, 3, "Hat 257"                          ),
    Hat258              (258u, 3, "Hat 258"                          ),
    Hat259              (259u, 3, "Hat 259"                          ),
    DiveBomber          (260u, 3, "Dive Bomber Hat"                  ),
    SeaShadow           (261u, 3, "Sea Shadow Hat"                   ),
    BurnCycle           (262u, 3, "Burn-Cycle Header"                ),
    ReefRipper          (263u, 3, "Reef Ripper Helmet"               ),
    JetStream           (264u, 3, "Jet Stream Helmet"                ),
    SodaSkimmer         (265u, 3, "Soda Skimmer Shower Cap"          ),
    TombBuggy           (266u, 3, "Tomb Buggy Skullcap"              ),
    StealthStinger      (267u, 3, "Stealth Stinger Beanie"           ),
    SharkTank           (268u, 3, "Shark Tank Topper"                ),
    GoldRusher          (269u, 3, "Gold Rusher Cog Cap"              ),
    SplatterSplasher    (270u, 3, "Splatter Splasher Spires"         ),
    ThumpTruck          (271u, 3, "Thump Trucker's Hat"              ),
    BuzzWing            (272u, 3, "Buzz Wing Hat"                    ),
    ShieldStriker       (273u, 3, "Shield Striker Helmet"            ),
    SunRunner           (274u, 3, "Sun Runner Spikes"                ),
    HotStreak           (275u, 3, "Hot Streak Headpiece"             ),
    SkySlicer           (276u, 3, "Sky Slicer Hat"                   ),
    CryptCrusher        (277u, 3, "Crypt Crusher Cap"                ),
    Mags                (278u, 3, "Mags Hat"                         ),
    KaosCrown           (279u, 3, "Kaos Krown"                       ),
    EonHelm             (280u, 3, "Eon's Helm"                       ),
    ;

    companion object {
        fun readFromData(hat1: UShort, hat2: UByte, hat3: UByte, hat5: UByte): Hat {
            var version: Int
            var ord: Int
            if (hat1 != 0.toUShort()) {
                version = 0
                ord = hat1.toInt()
            } else if (hat2 != 0.toUByte()) {
                version = 1
                ord = hat2.toInt()
            } else if (hat3 != 0.toUByte()) {
                version = 2
                ord = hat3.toInt()
            } else if (hat5 != 0.toUByte()) {
                version = 3
                ord = hat5.toInt() or 0x100
            } else {
                return None
            }

            val entry = Hat.entries.getOrElse(ord) {
                Log.e("Hat", "Invalid hat id: $ord")
                return None
            }
            if (entry.version == version) return entry
            else {
                Log.w("Hat", "Unknown hat value: version $version, id = $ord")
                return None
            }
        }
    }
}