package edu.jorbonism.nfclanders.enums

import android.util.Log

enum class Hat(val ord: UShort, val game: Game, val label: String) {
    None                (  0u, Game.SpyrosAdventure, ""                                 ),
    Army                (  1u, Game.SpyrosAdventure, "Combat Hat"                       ),
    French              (  2u, Game.SpyrosAdventure, "Napoleon Hat"                     ),
    Goggles             (  3u, Game.SpyrosAdventure, "Spy Gear"                         ),
    Mining              (  4u, Game.SpyrosAdventure, "Miner Hat"                        ),
    Officer             (  5u, Game.SpyrosAdventure, "General's Hat"                    ),
    Pirate              (  6u, Game.SpyrosAdventure, "Pirate Hat"                       ),
    Propeller           (  7u, Game.SpyrosAdventure, "Propeller Cap"                    ),
    Raccoon             (  8u, Game.SpyrosAdventure, "Coonskin Cap"                     ),
    Straw               (  9u, Game.SpyrosAdventure, "Straw Hat"                        ),
    Sunday              ( 10u, Game.SpyrosAdventure, "Fancy Hat (Monday)"               ),
    Tophat              ( 11u, Game.SpyrosAdventure, "Top Hat"                          ),
    Viking              ( 12u, Game.SpyrosAdventure, "Viking Helmet"                    ),
    WorldWarI           ( 13u, Game.SpyrosAdventure, "Spiked Hat"                       ),
    Anvil               ( 14u, Game.SpyrosAdventure, "Anvil Hat"                        ),
    Beret               ( 15u, Game.SpyrosAdventure, "Beret"                            ),
    BirthdayCap         ( 16u, Game.SpyrosAdventure, "Birthday Hat"                     ),
    Bonehead            ( 17u, Game.SpyrosAdventure, "Bone Head"                        ),
    Bowler              ( 18u, Game.SpyrosAdventure, "Bowler Hat"                       ),
    Bunny               ( 19u, Game.SpyrosAdventure, "Wabbit Ears"                      ),
    Carmen              ( 20u, Game.SpyrosAdventure, "Tropical Turban"                  ),
    Chef                ( 21u, Game.SpyrosAdventure, "Chef Hat"                         ),
    Cowboy              ( 22u, Game.SpyrosAdventure, "Cowboy Hat"                       ),
    CrazyHair           ( 23u, Game.SpyrosAdventure, "Rocker Hair"                      ),
    Crown               ( 24u, Game.SpyrosAdventure, "Royal Crown"                      ),
    DevilHorns          ( 25u, Game.SpyrosAdventure, "Lil' Devil"                       ),
    Eyeball             ( 26u, Game.SpyrosAdventure, "Eye Hat"                          ),
    Fez                 ( 27u, Game.SpyrosAdventure, "Fez"                              ),
    Halo                ( 28u, Game.SpyrosAdventure, "Crown of Light"                   ),
    Jester              ( 29u, Game.SpyrosAdventure, "Jester Hat"                       ),
    Mercury             ( 30u, Game.SpyrosAdventure, "Winged Hat"                       ),
    Moose               ( 31u, Game.SpyrosAdventure, "Moose Hat"                        ),
    Plunger             ( 32u, Game.SpyrosAdventure, "Plunger Head"                     ),
    Pot                 ( 33u, Game.SpyrosAdventure, "Pan Hat"                          ),
    Rocket              ( 34u, Game.SpyrosAdventure, "Rocket Hat"                       ),
    Santa               ( 35u, Game.SpyrosAdventure, "Santa Hat"                        ),
    Tiki                ( 36u, Game.SpyrosAdventure, "Tiki Hat"                         ),
    Trojan              ( 37u, Game.SpyrosAdventure, "Trojan Helmet"                    ),
    Unicorn             ( 38u, Game.SpyrosAdventure, "Unicorn Hat"                      ),
    Wizard              ( 39u, Game.SpyrosAdventure, "Wizard Hat (Spyro's Adventure)"   ),
    Pumpkin             ( 40u, Game.SpyrosAdventure, "Pumpkin Hat"                      ),
    PirateBandana       ( 41u, Game.SpyrosAdventure, "Pirate Doo Rag"                   ),
    Cossack             ( 42u, Game.SpyrosAdventure, "Cossack Hat"                      ),
    FlowerPot           ( 43u, Game.SpyrosAdventure, "Flower Hat"                       ),
    Balloon             ( 44u, Game.SpyrosAdventure, "Balloon Hat"                      ),
    BirthdayCake        ( 45u, Game.SpyrosAdventure, "Happy Birthday!"                  ),
    VintageBaseballCap  ( 46u, Game.Giants         , "Vintage Baseball Cap"             ),
    Hat47               ( 47u, Game.Giants         , "Hat 47"                           ),
    BowlingPin          ( 48u, Game.Giants         , "Bowling Pin Hat"                  ),
    Officer2            ( 49u, Game.Giants         , "Officer Cap"                      ),
    FirefighterHelmet   ( 50u, Game.Giants         , "Firefighter Helmet"               ),
    Graduation          ( 51u, Game.Giants         , "Graduation Hat"                   ),
    Lampshade           ( 52u, Game.Giants         , "Lampshade Hat"                    ),
    Mariachi            ( 53u, Game.Giants         , "Mariachi Hat"                     ),
    Hat54               ( 54u, Game.Giants         , "Hat 54"                           ),
    PaperFastFood       ( 55u, Game.Giants         , "Paper Fast Food Hat"              ),
    Pilgrim             ( 56u, Game.Giants         , "Pilgrim Hat"                      ),
    PoliceSiren         ( 57u, Game.Giants         , "Police Siren Hat"                 ),
    PurpleFedora        ( 58u, Game.Giants         , "Purple Fedora"                    ),
    Archer              ( 59u, Game.Giants         , "Archer Hat"                       ),
    Hat60               ( 60u, Game.Giants         , "Hat 60"                           ),
    Safari              ( 61u, Game.Giants         , "Safari Hat"                       ),
    Sailor              ( 62u, Game.Giants         , "Sailor Hat"                       ),
    Hat63               ( 63u, Game.Giants         , "Hat 63"                           ),
    Dancer              ( 64u, Game.Giants         , "Dancer Hat"                       ),
    TrafficCone         ( 65u, Game.Giants         , "Traffic Cone Hat"                 ),
    Turban              ( 66u, Game.Giants         , "Turban"                           ),
    BattleHelmet        ( 67u, Game.Giants         , "Battle Helmet"                    ),
    BottleCap           ( 68u, Game.Giants         , "Bottle Cap Hat"                   ),
    Hat69               ( 69u, Game.Giants         , "Hat 69"                           ),
    Carrot              ( 70u, Game.Giants         , "Carrot Hat"                       ),
    Hat71               ( 71u, Game.Giants         , "Hat 71"                           ),
    Elf                 ( 72u, Game.Giants         , "Elf Hat"                          ),
    Fishing             ( 73u, Game.Giants         , "Fishing Hat"                      ),
    Future              ( 74u, Game.Giants         , "Future Hat"                       ),
    Nefertiti           ( 75u, Game.Giants         , "Nefertiti"                        ),
    Hat76               ( 76u, Game.Giants         , "Hat 76"                           ),
    Pants               ( 77u, Game.Giants         , "Pants Hat"                        ),
    Princess            ( 78u, Game.Giants         , "Princess Hat"                     ),
    ToySoldier          ( 79u, Game.Giants         , "Toy Soldier Hat"                  ),
    Trucker             ( 80u, Game.Giants         , "Trucker Hat"                      ),
    Umbrella            ( 81u, Game.Giants         , "Umbrella Hat"                     ),
    Showtime            ( 82u, Game.Giants         , "Showtime Hat"                     ),
    Caesar              ( 83u, Game.Giants         , "Caesar Hat"                       ),
    FlowerFairy         ( 84u, Game.Giants         , "Flower Fairy Hat"                 ),
    Funnel              ( 85u, Game.Giants         , "Funnel Hat"                       ),
    Scrumshanks         ( 86u, Game.Giants         , "Scrumshanks Hat"                  ),
    Biter               ( 87u, Game.Giants         , "Biter Hat"                        ),
    Atom                ( 88u, Game.Giants         , "Atom Hat"                         ),
    Sombrero            ( 89u, Game.Giants         , "Sombrero"                         ),
    Rasta               ( 90u, Game.Giants         , "Rasta Hat"                        ),
    Kufi                ( 91u, Game.Giants         , "Kufi Hat"                         ),
    KnightHelm          ( 92u, Game.Giants         , "Knight Helm"                      ),
    DanglingCarrot      ( 93u, Game.Giants         , "Dangling Carrot Hat"              ),
    BronzeTopHat        ( 94u, Game.Giants         , "Bronze Top Hat"                   ),
    SilverTopHat        ( 95u, Game.Giants         , "Silver Top Hat"                   ),
    GoldTopHat          ( 96u, Game.Giants         , "Gold Top Hat"                     ),
    Rain                ( 97u, Game.SwapForce      , "Rain Hat"                         ),
    SnorkelingMask      ( 98u, Game.SwapForce      , "The Outsider"                     ),
    Greeble             ( 99u, Game.SwapForce      , "Greeble Hat"                      ),
    Volcano             (100u, Game.SwapForce      , "Volcano Hat"                      ),
    Boater              (101u, Game.SwapForce      , "Boater Hat"                       ),
    Stone               (102u, Game.SwapForce      , "Stone Hat"                        ),
    Stovepipe           (103u, Game.SwapForce      , "Stovepipe Hat"                    ),
    Boonie              (104u, Game.SwapForce      , "Boonie Hat"                       ),
    Sawblade            (105u, Game.SwapForce      , "Sawblade Hat"                     ),
    SunBonnet           (106u, Game.SwapForce      , "Zombeanie Hat"                    ),
    Gaucho              (107u, Game.SwapForce      , "Gaucho Hat"                       ),
    Roundlet            (108u, Game.SwapForce      , "Roundlet Hat"                     ),
    Capuchon            (109u, Game.SwapForce      , "Capuchon"                         ),
    Tricorn             (110u, Game.SwapForce      , "Tricorn Hat"                      ),
    FeatheredHeaddress  (111u, Game.SwapForce      , "Feathered Headdress (Peacock Hat)"),
    BearskinCap         (112u, Game.SwapForce      , "Bearskin Cap"                     ),
    Fishbone            (113u, Game.SwapForce      , "Fishbone Hat"                     ),
    SkiCap              (114u, Game.SwapForce      , "Ski Cap"                          ),
    CrownOfFrost        (115u, Game.SwapForce      , "Crown of Frost"                   ),
    FourWinds           (116u, Game.SwapForce      , "Four Winds Hat"                   ),
    Beacon              (117u, Game.SwapForce      , "Beacon Hat"                       ),
    FlowerGarland       (118u, Game.SwapForce      , "Flower Garland"                   ),
    TreeBranch          (119u, Game.SwapForce      , "Tree Branch"                      ),
    AviatorsCap         (120u, Game.SwapForce      , "Aviator's Cap"                    ),
    Asteroid            (121u, Game.SwapForce      , "Asteroid Hat"                     ),
    Crystal             (122u, Game.SwapForce      , "Crystal Hat"                      ),
    CreepyHelm          (123u, Game.SwapForce      , "Creepy Helm"                      ),
    FancyRibbon         (124u, Game.SwapForce      , "Fancy Ribbon"                     ),
    DeelyBoppers        (125u, Game.SwapForce      , "Deely Boppers"                    ),
    BeanieCap           (126u, Game.SwapForce      , "Beanie"                           ),
    Leprechaun          (127u, Game.SwapForce      , "Leprechaun Hat"                   ),
    Shark               (128u, Game.SwapForce      , "Shark Hat (Sharkfin Hat)"         ),
    LifePreserver       (129u, Game.SwapForce      , "Life Preserver Hat"               ),
    GlitteringTiara     (130u, Game.SwapForce      , "Glittering Tiara"                 ),
    GreatHelm           (131u, Game.SwapForce      , "Great Helm"                       ),
    SpaceHelmet         (132u, Game.SwapForce      , "Space Helmet"                     ),
    UFO                 (133u, Game.SwapForce      , "UFO Hat"                          ),
    WhirlwindDiadem     (134u, Game.SwapForce      , "Whirlwind Diadem"                 ),
    ObsidianHelm        (135u, Game.SwapForce      , "Obsidian Helm"                    ),
    Lilypad             (136u, Game.SwapForce      , "Lilypad Hat"                      ),
    CrownOfFlames       (137u, Game.SwapForce      , "Crown of Flames"                  ),
    RunicHeadband       (138u, Game.SwapForce      , "Runic Headband"                   ),
    Clockwork           (139u, Game.SwapForce      , "Clockwork Hat"                    ),
    Cactus              (140u, Game.SwapForce      , "Cactus Hat"                       ),
    SkullHelm           (141u, Game.SwapForce      , "Skullhelm (Skyll)"                ),
    Gloop               (142u, Game.SwapForce      , "Gloop Hat"                        ),
    Puma                (143u, Game.SwapForce      , "Puma Hat"                         ),
    Elephant            (144u, Game.SwapForce      , "Elephant Hat"                     ),
    TigerSkin           (145u, Game.SwapForce      , "Tiger Skin Cap"                   ),
    TeethTop            (146u, Game.SwapForce      , "Teeth Top Hat"                    ),
    Turkey              (147u, Game.SwapForce      , "Turkey Hat"                       ),
    Afro                (148u, Game.SwapForce      , "Eyefro"                           ),
    BaconBandana        (149u, Game.SwapForce      , "Bacon Bandana"                    ),
    AwesomeHat          (150u, Game.SwapForce      , "Awesome Hat"                      ),
    CardShark           (151u, Game.SwapForce      , "Card Shark Hat"                   ),
    EasterTriggerHappy  (152u, Game.SwapForce      , "Springtime Hat"                   ),
    HolidayBumbleBlast  (153u, Game.SwapForce      , "Jolly Hat"                        ),
    SoccerCountdown     (154u, Game.SwapForce      , "Kickoff Hat"                      ),
    Beetle              (155u, Game.TrapTeam       , "Beetle Hat"                       ),
    Brain               (156u, Game.TrapTeam       , "Brain Hat"                        ),
    Brainiac            (157u, Game.TrapTeam       , "Brainiac Hat"                     ),
    Bucket              (158u, Game.TrapTeam       , "Bucket Hat"                       ),
    Cactus02            (159u, Game.TrapTeam       , "Desert Crown"                     ),
    Fan                 (160u, Game.TrapTeam       , "Ceiling Fan Hat"                  ),
    Chinese             (161u, Game.TrapTeam       , "Imperial Hat"                     ),
    Clown               (162u, Game.TrapTeam       , "Clown Classic Hat"                ),
    ClownBowler         (163u, Game.TrapTeam       , "Clown Bowler Hat"                 ),
    Colander            (164u, Game.TrapTeam       , "Colander Hat"                     ),
    Kepi                (165u, Game.TrapTeam       , "Kepi Hat"                         ),
    Cornucopia          (166u, Game.TrapTeam       , "Cornucopia Hat"                   ),
    Cubano              (167u, Game.TrapTeam       , "Cubano Hat"                       ),
    Cycling             (168u, Game.TrapTeam       , "Cycling Hat"                      ),
    DaisyCrown          (169u, Game.TrapTeam       , "Daisy Crown"                      ),
    Skull               (170u, Game.TrapTeam       , "Dragon Skull"                     ),
    DundeeSlouch        (171u, Game.TrapTeam       , "Outback Hat"                      ),
    ElfMini             (172u, Game.TrapTeam       , "Lil' Elf Hat"                     ),
    Castro              (173u, Game.TrapTeam       , "Generalissimo"                    ),
    Garrison            (174u, Game.TrapTeam       , "Garrison Hat"                     ),
    Gondolier           (175u, Game.TrapTeam       , "Gondolier Hat"                    ),
    Hunting             (176u, Game.TrapTeam       , "Hunting Hat"                      ),
    Juicer              (177u, Game.TrapTeam       , "Juicer Hat"                       ),
    Kokoshnik           (178u, Game.TrapTeam       , "Kokoshnik"                        ),
    Medic               (179u, Game.TrapTeam       , "Medic Hat"                        ),
    Melon               (180u, Game.TrapTeam       , "Melon Hat"                        ),
    Mountie             (181u, Game.TrapTeam       , "Mountie Hat"                      ),
    Nurse               (182u, Game.TrapTeam       , "Nurse Hat"                        ),
    Palm                (183u, Game.TrapTeam       , "Palm Hat"                         ),
    Paperboy            (184u, Game.TrapTeam       , "Paperboy Hat"                     ),
    ParrotRoosting      (185u, Game.TrapTeam       , "Parrot Nest"                      ),
    Projector           (186u, Game.TrapTeam       , "Old-Time Movie Hat"               ),
    Pot02               (187u, Game.TrapTeam       , "Classic Pot Hat"                  ),
    Radar               (188u, Game.TrapTeam       , "Radar Hat"                        ),
    Tiara               (189u, Game.TrapTeam       , "Crazy Light Bulb Hat"             ),
    RubberGlove         (190u, Game.TrapTeam       , "Rubber Glove Hat"                 ),
    Rugby               (191u, Game.TrapTeam       , "Rugby Hat"                        ),
    SharkFin            (192u, Game.TrapTeam       , "Metal Fin Hat"                    ),
    Sherlock            (193u, Game.TrapTeam       , "Sleuth Hat"                       ),
    Shower              (194u, Game.TrapTeam       , "Shower Cap"                       ),
    Bobby               (195u, Game.TrapTeam       , "Bobby"                            ),
    Hedgehog            (196u, Game.TrapTeam       , "Hedgehog Hat"                     ),
    Steampunk           (197u, Game.TrapTeam       , "Steampunk Hat"                    ),
    Stewardess          (198u, Game.TrapTeam       , "Flight Attendant Hat"             ),
    SundayFancy         (199u, Game.TrapTeam       , "Monday Hat"                       ),
    Tibet               (200u, Game.TrapTeam       , "Sherpa Hat"                       ),
    Trash               (201u, Game.TrapTeam       , "Trash Lid"                        ),
    Turtle              (202u, Game.TrapTeam       , "Turtle Hat"                       ),
    UFO02               (203u, Game.TrapTeam       , "Extreme Viking Hat"               ),
    Vespa               (204u, Game.TrapTeam       , "Scooter Hat"                      ),
    Volcano02           (205u, Game.TrapTeam       , "Volcano Island Hat"               ),
    WaterBallet         (206u, Game.TrapTeam       , "Synchronized Swimming Cap"        ),
    WilliamTell         (207u, Game.TrapTeam       , "William Tell Hat"                 ),
    Zulu                (208u, Game.TrapTeam       , "Tribal Hat"                       ),
    RudeBoyChecker      (209u, Game.TrapTeam       , "Rude Boy Hat"                     ),
    PorkPieChecker      (210u, Game.TrapTeam       , "Pork Pie Hat"                     ),
    AlarmClock          (211u, Game.TrapTeam       , "Alarm Clock Hat"                  ),
    Armadillo           (212u, Game.TrapTeam       , "Batter Up Hat"                    ),
    BearTrap            (213u, Game.TrapTeam       , "Horns Be With You"                ),
    Croissant           (214u, Game.TrapTeam       , "Croissant Hat"                    ),
    WeatherVane         (215u, Game.TrapTeam       , "Weather Vane Hat"                 ),
    Rainbow             (216u, Game.TrapTeam       , "Rainbow Hat"                      ),
    EyeOfKaos           (217u, Game.TrapTeam       , "Eye of Kaos Hat"                  ),
    BatEars             (218u, Game.TrapTeam       , "Bat Hat"                          ),
    Lightbulb           (219u, Game.TrapTeam       , "Light Bulb"                       ),
    Fireflies           (220u, Game.TrapTeam       , "Firefly Jar"                      ),
    ShadowGhost         (221u, Game.TrapTeam       , "Shadow Ghost Hat"                 ),
    Lighthouse          (222u, Game.TrapTeam       , "Lighthouse Beacon Hat"            ),
    TinFoil             (223u, Game.TrapTeam       , "Tin Foil Hat"                     ),
    NightCap            (224u, Game.TrapTeam       , "Night Cap"                        ),
    Storm               (225u, Game.TrapTeam       , "Storm Hat"                        ),
    KnightmareGold      (226u, Game.TrapTeam       , "Gold Arkeyan Helm"                ),
    Duck                (227u, Game.TrapTeam       , "Toucan Hat"                       ),
    Pyramid             (228u, Game.TrapTeam       , "Pyramid Hat"                      ),
    Windmill            (229u, Game.TrapTeam       , "Miniature Skylands Hat"           ),
    Wizard02            (230u, Game.TrapTeam       , "Wizard Hat (Trap Team)"           ),
    Hat231              (231u, Game.TrapTeam       , "Hat 231"                          ),
    Confectioner        (232u, Game.TrapTeam       , "Candy Cane Hat"                   ),
    Eggshell            (233u, Game.TrapTeam       , "Eggshell Hat"                     ),
    Candle              (234u, Game.TrapTeam       , "Candle Hat"                       ),
    HelmDark            (235u, Game.TrapTeam       , "Dark Helm"                        ),
    Orbit               (236u, Game.TrapTeam       , "Planet Hat"                       ),
    Bellhop             (237u, Game.TrapTeam       , "Bellhop Hat"                      ),
    KnightmareBronze    (238u, Game.TrapTeam       , "Bronze Arkeyan Helm"              ),
    KnightmareSilver    (239u, Game.TrapTeam       , "Silver Arkeyan Helm"              ),
    Raver               (240u, Game.TrapTeam       , "Raver Hat"                        ),
    Shire               (241u, Game.TrapTeam       , "Shire Hat"                        ),
    Mongol              (242u, Game.TrapTeam       , "Mongol Hat"                       ),
    FishermanSlicker    (243u, Game.TrapTeam       , "Skipper Hat"                      ),
    MedievalBard        (244u, Game.TrapTeam       , "Medieval Bard Hat"                ),
    Wooden              (245u, Game.TrapTeam       , "Wooden Hat"                       ),
    Carnival            (246u, Game.TrapTeam       , "Carnival Hat"                     ),
    Coconut             (247u, Game.TrapTeam       , "Coconut Hat"                      ),
    Wilikin             (248u, Game.TrapTeam       , "Model Home Hat"                   ),
    Frostfest           (249u, Game.TrapTeam       , "Ice Cream Hat"                    ),
    Molekin             (250u, Game.TrapTeam       , "Molekin Mountain Hat"             ),
    Sheepwrecked        (251u, Game.TrapTeam       , "Sheepwrecked Hat"                 ),
    OldRuins            (252u, Game.TrapTeam       , "Core of Light Hat"                ),
    Oracle              (253u, Game.TrapTeam       , "Octavius Cloptimus Hat"           ),
    Hat254              (254u, Game.TrapTeam       , "Hat 254"                          ),
    Hat255              (255u, Game.TrapTeam       , "Hat 255"                          ),
    Hat256              (256u, Game.Superchargers  , "Hat 256"                          ),
    Hat257              (257u, Game.Superchargers  , "Hat 257"                          ),
    Hat258              (258u, Game.Superchargers  , "Hat 258"                          ),
    Hat259              (259u, Game.Superchargers  , "Hat 259"                          ),
    DiveBomber          (260u, Game.Superchargers  , "Dive Bomber Hat"                  ),
    SeaShadow           (261u, Game.Superchargers  , "Sea Shadow Hat"                   ),
    BurnCycle           (262u, Game.Superchargers  , "Burn-Cycle Header"                ),
    ReefRipper          (263u, Game.Superchargers  , "Reef Ripper Helmet"               ),
    JetStream           (264u, Game.Superchargers  , "Jet Stream Helmet"                ),
    SodaSkimmer         (265u, Game.Superchargers  , "Soda Skimmer Shower Cap"          ),
    TombBuggy           (266u, Game.Superchargers  , "Tomb Buggy Skullcap"              ),
    StealthStinger      (267u, Game.Superchargers  , "Stealth Stinger Beanie"           ),
    SharkTank           (268u, Game.Superchargers  , "Shark Tank Topper"                ),
    GoldRusher          (269u, Game.Superchargers  , "Gold Rusher Cog Cap"              ),
    SplatterSplasher    (270u, Game.Superchargers  , "Splatter Splasher Spires"         ),
    ThumpTruck          (271u, Game.Superchargers  , "Thump Trucker's Hat"              ),
    BuzzWing            (272u, Game.Superchargers  , "Buzz Wing Hat"                    ),
    ShieldStriker       (273u, Game.Superchargers  , "Shield Striker Helmet"            ),
    SunRunner           (274u, Game.Superchargers  , "Sun Runner Spikes"                ),
    HotStreak           (275u, Game.Superchargers  , "Hot Streak Headpiece"             ),
    SkySlicer           (276u, Game.Superchargers  , "Sky Slicer Hat"                   ),
    CryptCrusher        (277u, Game.Superchargers  , "Crypt Crusher Cap"                ),
    Mags                (278u, Game.Superchargers  , "Mags Hat"                         ),
    KaosCrown           (279u, Game.Superchargers  , "Kaos Krown"                       ),
    EonHelm             (280u, Game.Superchargers  , "Eon's Helm"                       ),
    ;

    fun getData(): Array<UByte> {
        return when (game) {
            Game.SpyrosAdventure -> arrayOf(ord.toUByte(), 0u, 0u, 0u)
            Game.Giants          -> arrayOf(0u, ord.toUByte(), 0u, 0u)
            Game.SwapForce       -> arrayOf(0u, 0u, ord.toUByte(), 0u)
            Game.TrapTeam        -> arrayOf(0u, 0u, ord.toUByte(), 0u)
            Game.Superchargers   -> arrayOf(0u, 0u, 0u, (ord and 0xffu).toUByte())
            else -> arrayOf(0u, 0u, 0u, 0u)
        }
    }

    companion object {
        fun readFromData(hat1: UShort, hat2: UByte, hat3: UByte, hat5: UByte): Hat {
            var game: Game
            var ord: Int
            if (hat1 != 0.toUShort()) {
                game = Game.SpyrosAdventure
                ord = hat1.toInt()
            } else if (hat2 != 0.toUByte()) {
                game = Game.Giants
                ord = hat2.toInt()
            } else if (hat3 != 0.toUByte()) {
                game = if (hat3 < 155u) Game.SwapForce else Game.TrapTeam
                ord = hat3.toInt()
            } else if (hat5 != 0.toUByte()) {
                game = Game.Superchargers
                ord = hat5.toInt() or 0x100
            } else {
                return None
            }

            val entry = Hat.entries.getOrElse(ord) {
                Log.e("Hat", "Invalid hat id: $ord")
                return None
            }
            if (entry.game == game) return entry
            else {
                Log.w("Hat", "Unknown hat value: id = $ord ($game)")
                return None
            }
        }
    }
}