package edu.jorbonism.nfclanders.enums

enum class HeroicChallenge(val ord: UByte, val game: Game, val label: String) {
    SSA00( 0u, Game.SpyrosAdventure, "Chompy Chomp Down"         ),
    SSA01( 1u, Game.SpyrosAdventure, "This Bomb's For You"       ),
    SSA02( 2u, Game.SpyrosAdventure, "Jump For It!"              ),
    SSA03( 3u, Game.SpyrosAdventure, "Where Art Thou, Paintings" ),
    SSA04( 4u, Game.SpyrosAdventure, "Lair of the Giant Spiders" ),
    SSA05( 5u, Game.SpyrosAdventure, "Fight, Teleport, Fight!"   ),
    SSA06( 6u, Game.SpyrosAdventure, "The Three Teleporters"     ),
    SSA07( 7u, Game.SpyrosAdventure, "Stop, Sheep Thieves!"      ),
    SSA08( 8u, Game.SpyrosAdventure, "Mining for Charms"         ),
    SSA09( 9u, Game.SpyrosAdventure, "Dungeoness Creeps"         ),
    SSA10(10u, Game.SpyrosAdventure, "Mining is the Key"         ),
    SSA11(11u, Game.SpyrosAdventure, "Mission Achomplished"      ),
    SSA12(12u, Game.SpyrosAdventure, "Pod Gauntlet"              ),
    SSA13(13u, Game.SpyrosAdventure, "Time's A-Wastin'"          ),
    SSA14(14u, Game.SpyrosAdventure, "Save the Purple Chompies!" ),
    SSA15(15u, Game.SpyrosAdventure, "Spawner Cave"              ),
    SSA16(16u, Game.SpyrosAdventure, "Arachnid Antechamber"      ),
    SSA17(17u, Game.SpyrosAdventure, "Hobson's Choice"           ),
    SSA18(18u, Game.SpyrosAdventure, "Isle of the Automatons"    ),
    SSA19(19u, Game.SpyrosAdventure, "You Break It, You Buy It!" ),
    SSA20(20u, Game.SpyrosAdventure, "Minefield Mishap"          ),
    SSA21(21u, Game.SpyrosAdventure, "Lobs O' Fun"               ),
    SSA22(22u, Game.SpyrosAdventure, "Spell Punked!"             ),
    SSA23(23u, Game.SpyrosAdventure, "Charm Hunt"                ),
    SSA24(24u, Game.SpyrosAdventure, "Flip the Script"           ),
    SSA25(25u, Game.SpyrosAdventure, "You've Stolen My Hearts!"  ),
    SSA26(26u, Game.SpyrosAdventure, "Bombs to the Walls"        ),
    SSA27(27u, Game.SpyrosAdventure, "Operation: Sheep Freedom"  ),
    SSA28(28u, Game.SpyrosAdventure, "Jailbreak!"                ),
    SSA29(29u, Game.SpyrosAdventure, "Environmentally Unfriendly"),
    SSA30(30u, Game.SpyrosAdventure, "Chemical Cleanup"          ),
    SSA31(31u, Game.SpyrosAdventure, "Break the Cats"            ),
    SG00 (32u, Game.Giants         , "Flame Pirates on Ice"      ),
    SG01 (33u, Game.Giants         , "Skylands Salute"           ),
    SG02 (34u, Game.Giants         , "S.A.B.R.I.N.A"             ),
    SG03 (35u, Game.Giants         , "The Sky is Falling"        ),
    SG04 (36u, Game.Giants         , "Nort's Winter Classic"     ),
    SG05 (37u, Game.Giants         , "Break the Fakes!"          ),
    SG06 (38u, Game.Giants         , "Baking with Batterson"     ),
    SG07 (39u, Game.Giants         , "Blobber's Folly"           ),
    SG08 (40u, Game.Giants         , "Unused Heroic 40"          ),
    SG09 (41u, Game.Giants         , "Unused Heroic 41"          ),
    SG10 (42u, Game.Giants         , "Unused Heroic 42"          ),
    SG11 (43u, Game.Giants         , "Unused Heroic 43"          ),
    SG12 (44u, Game.Giants         , "Unused Heroic 44"          ),
    SG13 (45u, Game.Giants         , "Unused Heroic 45"          ),
    SG14 (46u, Game.Giants         , "Delivery Day"              ),
    SG15 (47u, Game.Giants         , "Give a Hoot"               ),
    SG16 (48u, Game.Giants         , "Zombie Dance Party"        ),
    SG17 (49u, Game.Giants         , "Shepherd's Pie"            ),
    SG18 (50u, Game.Giants         , "Watermelon's Eleven"       ),
    SG19 (51u, Game.Giants         , "A Real Goat-Getter"        ),
    SG20 (52u, Game.Giants         , "Wooly Bullies"             ),
    SG21 (53u, Game.Giants         , "The Great Pancake Slalom"  ),
    SG22 (54u, Game.Giants         , "Shoot First, Shoot Later"  ),
    SG23 (55u, Game.Giants         , "The King's Breech"         ),
}
