package edu.jorbonism.nfclanders.enums

public enum class Game(val ord: UByte) {
    SpyrosAdventure(0u),
    Giants(1u),
    SwapForce(2u),
    TrapTeam(3u),
    SuperChargers(4u),
    Imaginators(5u),
}

public enum class CharacterType {
    Character,
    Legendary,
    Item,
    Expansion,
    Sidekick,
    SwapLegs,
    SwapBody,
    Trap,
    Mini,
    Vehicle,
    VillainDriver,
    VillainVehicle,
    Trophy,
}

public enum class Playability {
    Normal,
    NotPlayable,
    Debug,
}

enum class Deco(val ord: UByte, val label: String) {
    Normal              ( 0u, "Normal"            ),
    Repose1             ( 1u, "Repose 1"          ),
    Alternate           ( 2u, "Alternate Deco"    ),
    Legendary           ( 3u, "Legendary"         ),
    Event               ( 4u, "Event"             ),
    Repose2             ( 5u, "Repose 2"          ),
    LightDirect         ( 6u, "Light Direct"      ),
    LightStored         ( 7u, "Light Stored"      ),
    LightEnhanced       ( 8u, "Light Enhanced"    ),
    Repose3             ( 9u, "Repose 3"          ),
    Repose4             (10u, "Repose 4"          ),
    Repose5             (11u, "Repose 5"          ),
    Valentines          (12u, "Valentine's"       ),
    Easter              (13u, "Easter"            ),
    Winter              (14u, "Winter"            ),
    Virtual             (15u, "Virtual"           ),
    Premium             (16u, "Premium"           ),
    GlowDark            (17u, "Glow in the Dark"  ),
    StoneStatue         (18u, "Stone Statue"      ),
    GlitterSpectrum     (19u, "Glitter Spectrum"  ),
    TreasureHunt2012    (20u, "Treasure Hunt 2012"),
    Halloween           (21u, "Halloween"         ),
    TreasureHunt2013    (22u, "Treasure Hunt 2013"),
    ColorShift          (23u, "Color Shift"       ),
    WiiU                (24u, "Wii U"             ),
    BestBuy             (25u, "Best Buy"          ),
    FritoLay            (26u, "Frito Lay"         ),
    Deco27              (27u, "Deco 27"           ),
    Deco28              (28u, "Deco 28"           ),
    TreasureHunt2014    (29u, "Treasure Hunt 2014"),
    TreasureHunt2015    (30u, "Treasure Hunt 2015"),
    Mobile              (31u, "Mobile"            ),
}

enum class Trinket(val ord: UByte, label: String) {
    None                    ( 0u, ""                          ),
    LuckyTie                ( 1u, "T-Bone's Lucky Tie"        ),
    Bubble                  ( 2u, "Batterson's Bubble"        ),
    DarkWaterDaisy          ( 3u, "Dark Water Daisy"          ),
    VoteForCyclops          ( 4u, "Vote for Cyclops"          ),
    DragonHorn              ( 5u, "Ramses' Dragon Horn"       ),
    Iris                    ( 6u, "Iris' Iris"                ),
    KuckooKazoo             ( 7u, "Kuckoo Kazoo"              ),
    Rune                    ( 8u, "Ramses' Rune"              ),
    UllyssesUniclops        ( 9u, "Ullysses Uniclops"         ),
    BillyBison              (10u, "Billy Bison"               ),
    StealthElfGift          (11u, "Stealth Elf's Gift"        ),
    LizardLilly             (12u, "Lizard Lilly"              ),
    PiratePinwheel          (13u, "Pirate Pinwheel"           ),
    BubbleBlower            (14u, "Bubble Blower"             ),
    MedalOfHeroism          (15u, "Medal of Heroism"          ),
    MedalOfCourage          (16u, "Blobbers' Medal of Courage"),
    MedalOfValiance         (17u, "Medal of Valiance"         ),
    MedalOfGallantry        (18u, "Medal of Gallantry"        ),
    MedalOfMettle           (19u, "Medal of Mettle"           ),
    WingedMedalOfBravery    (20u, "Winged Medal of Bravery"   ),
    SeadogSeashell          (21u, "Seadog Seashell"           ),
    Sunflower               (22u, "Snuckles' Sunflower"       ),
    TeddyCyclops            (23u, "Teddy Cyclops"             ),
    GooFactoryGear          (24u, "Goo Factory Gear"          ),
    ElementalOpal           (25u, "Elemental Opal"            ),
    ElementalRadiant        (26u, "Elemental Radiant"         ),
    ElementalDiamond        (27u, "Elemental Diamond"         ),
    CyclopsSpinner          (28u, "Cyclops Spinner"           ),
    WilikinWindmill         (29u, "Wilikin Windmill"          ),
    TimeTownTicker          (30u, "Time Town Ticker"          ),
    BigBowOfBoom            (31u, "Big Bow of Boom"           ),
    MabusMedallion          (32u, "Mabu's Medallion"          ),
    SpyrosShield            (33u, "Spyro's Shield"            ),
}

enum class HericChallenge(val ord: UByte, val game: Game, val label: String) {
    SSA00( 0u, Game.SpyrosAdventure, "Chompy Chomp Down"         ),
    SSA01( 1u, Game.SpyrosAdventure, "This Bomb's For You"       ),
    SSA02( 2u, Game.SpyrosAdventure, "Jump For It!"              ),
    SSA03( 3u, Game.SpyrosAdventure, "Where Art Thou, Paintings" ),
    SSA04( 4u, Game.SpyrosAdventure, "Lair of the Giant Spiders" ),
    SSA05( 5u, Game.SpyrosAdventure, "Fight, Teleport, Fight!"   ),
    SSA06( 6u, Game.SpyrosAdventure, "The Three Teleporters"     ),
    SSA07( 7u, Game.SpyrosAdventure, "Stop, Sheep Thieves!"      ),
    SSA08( 8u, Game.SpyrosAdventure, "Mining for Charms"         ),
    SSA09( 9u, Game.SpyrosAdventure, "Dungeoness Creeps"         ),
    SSA10(10u, Game.SpyrosAdventure, "Mining is the Key"         ),
    SSA11(11u, Game.SpyrosAdventure, "Mission Achomplished"      ),
    SSA12(12u, Game.SpyrosAdventure, "Pod Gauntlet"              ),
    SSA13(13u, Game.SpyrosAdventure, "Time's A-Wastin'"          ),
    SSA14(14u, Game.SpyrosAdventure, "Save the Purple Chompies!" ),
    SSA15(15u, Game.SpyrosAdventure, "Spawner Cave"              ),
    SSA16(16u, Game.SpyrosAdventure, "Arachnid Antechamber"      ),
    SSA17(17u, Game.SpyrosAdventure, "Hobson's Choice"           ),
    SSA18(18u, Game.SpyrosAdventure, "Isle of the Automatons"    ),
    SSA19(19u, Game.SpyrosAdventure, "You Break It, You Buy It!" ),
    SSA20(20u, Game.SpyrosAdventure, "Minefield Mishap"          ),
    SSA21(21u, Game.SpyrosAdventure, "Lobs O' Fun"               ),
    SSA22(22u, Game.SpyrosAdventure, "Spell Punked!"             ),
    SSA23(23u, Game.SpyrosAdventure, "Charm Hunt"                ),
    SSA24(24u, Game.SpyrosAdventure, "Flip the Script"           ),
    SSA25(25u, Game.SpyrosAdventure, "You've Stolen My Hearts!"  ),
    SSA26(26u, Game.SpyrosAdventure, "Bombs to the Walls"        ),
    SSA27(27u, Game.SpyrosAdventure, "Operation: Sheep Freedom"  ),
    SSA28(28u, Game.SpyrosAdventure, "Jailbreak!"                ),
    SSA29(29u, Game.SpyrosAdventure, "Environmentally Unfriendly"),
    SSA30(30u, Game.SpyrosAdventure, "Chemical Cleanup"          ),
    SSA31(31u, Game.SpyrosAdventure, "Break the Cats"            ),
    SG00 (32u, Game.Giants         , "Flame Pirates on Ice"      ),
    SG01 (33u, Game.Giants         , "Skylands Salute"           ),
    SG02 (34u, Game.Giants         , "S.A.B.R.I.N.A"             ),
    SG03 (35u, Game.Giants         , "The Sky is Falling"        ),
    SG04 (36u, Game.Giants         , "Nort's Winter Classic"     ),
    SG05 (37u, Game.Giants         , "Break the Fakes!"          ),
    SG06 (38u, Game.Giants         , "Baking with Batterson"     ),
    SG07 (39u, Game.Giants         , "Blobber's Folly"           ),
    SG08 (40u, Game.Giants         , "Unused Heroic 40"          ),
    SG09 (41u, Game.Giants         , "Unused Heroic 41"          ),
    SG10 (42u, Game.Giants         , "Unused Heroic 42"          ),
    SG11 (43u, Game.Giants         , "Unused Heroic 43"          ),
    SG12 (44u, Game.Giants         , "Unused Heroic 44"          ),
    SG13 (45u, Game.Giants         , "Unused Heroic 45"          ),
    SG14 (46u, Game.Giants         , "Delivery Day"              ),
    SG15 (47u, Game.Giants         , "Give a Hoot"               ),
    SG16 (48u, Game.Giants         , "Zombie Dance Party"        ),
    SG17 (49u, Game.Giants         , "Shepherd's Pie"            ),
    SG18 (50u, Game.Giants         , "Watermelon's Eleven"       ),
    SG19 (51u, Game.Giants         , "A Real Goat-Getter"        ),
    SG20 (52u, Game.Giants         , "Wooly Bullies"             ),
    SG21 (53u, Game.Giants         , "The Great Pancake Slalom"  ),
    SG22 (54u, Game.Giants         , "Shoot First, Shoot Later"  ),
    SG23 (55u, Game.Giants         , "The King's Breech"         ),
}
