package edu.jorbonism.nfclanders.enums

import edu.jorbonism.nfclanders.getFlag
import edu.jorbonism.nfclanders.numberFromFlags

data class ToyType(
    val name        : String,
    val characterID : UInt,
    val game        : Game,
    val deco        : Deco = Deco.Normal,
    val repose      : Boolean = false,
    val variant     : Boolean = false,
    val lightcore   : Boolean = false,
    val supercharger: Boolean = false,
) {
    fun variantFlagByte(): Byte {
        return ((game.ord.toULong() shl 4) or numberFromFlags(arrayOf(supercharger, lightcore, variant, repose))).toByte()
    }

    companion object {
        fun fromData(characterID: UInt, decoID: Byte, flags: Byte): ToyType {
            val deco = Deco.entries[decoID.toInt()]
            val game = Game.entries[(flags.toInt() shr 4) and 0b1111]
            val repose       = getFlag(flags, 3)
            val variant      = getFlag(flags, 2)
            val lightcore    = getFlag(flags, 1)
            val supercharger = getFlag(flags, 0)

            for (entry in table) {
                if (
                    entry.characterID  == characterID  &&
                    entry.deco         == deco         &&
                    entry.game         == game         &&
                    entry.repose       == repose       &&
                    entry.variant      == variant      &&
                    entry.lightcore    == lightcore    &&
                    entry.supercharger == supercharger
                ) return entry
            }
            return ToyType("Unknown", characterID, game, deco, repose, variant, lightcore, supercharger)
        }

        val table: Array<ToyType> = arrayOf(
            ToyType("Whirlwind"                                , Character.Whirlwind            .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Crystal Clear Whirlwind"                  , Character.Whirlwind            .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Sonic Boom"                               , Character.SonicBoom            .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Warnado"                                  , Character.Warnado              .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Glow-in-the-Dark Warnado"                 , Character.Warnado              .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Lightning Rod"                            , Character.LightningRod         .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Bash"                                     , Character.Bash                 .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Blue Bash"                                , Character.Bash                 .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Terrafin"                                 , Character.Terrafin             .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Dino-Rang"                                , Character.DinoRang             .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Silver Dino-Rang"                         , Character.DinoRang             .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Prism Break"                              , Character.PrismBreak           .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Sunburn"                                  , Character.Sunburn              .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Eruptor"                                  , Character.Eruptor              .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Silver Eruptor"                           , Character.Eruptor              .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Ignitor"                                  , Character.Ignitor              .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Flameslinger"                             , Character.Flameslinger         .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Gold Flameslinger"                        , Character.Flameslinger         .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Zap"                                      , Character.Zap                  .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Glow-in-the-Dark Zap"                     , Character.Zap                  .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Wham-Shell"                               , Character.WhamShell            .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Crystal Clear Wham-Shell"                 , Character.WhamShell            .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Gill Grunt"                               , Character.GillGrunt            .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Green Gill Grunt"                         , Character.GillGrunt            .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Slam Bam"                                 , Character.SlamBam              .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Spyro"                                    , Character.Spyro                .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Chrome Spyro"                             , Character.Spyro                .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Voodood"                                  , Character.Voodood              .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Double Trouble"                           , Character.DoubleTrouble        .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Trigger Happy"                            , Character.TriggerHappy         .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Drobot"                                   , Character.Drobot               .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Drill Sergeant"                           , Character.DrillSergeant        .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Gold Drill Sergeant"                      , Character.DrillSergeant        .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Red Drill Sergeant"                       , Character.DrillSergeant        .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Boomer"                                   , Character.Boomer               .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Silver Boomer"                            , Character.Boomer               .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Wrecking Ball"                            , Character.WreckingBall         .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Glow-in-the-Dark Wrecking Ball"           , Character.WreckingBall         .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Camo"                                     , Character.Camo                 .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Red Camo"                                 , Character.Camo                 .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Zook"                                     , Character.Zook                 .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Stealth Elf"                              , Character.StealthElf           .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Crystal Clear Stealth Elf"                , Character.StealthElf           .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Stump Smash"                              , Character.StumpSmash           .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Flocked Stump Smash"                      , Character.StumpSmash           .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Dark Spyro"                               , Character.DarkSpyro            .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Hex"                                      , Character.Hex                  .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Pearl Hex"                                , Character.Hex                  .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Chop Chop"                                , Character.ChopChop             .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Gold Chop Chop"                           , Character.ChopChop             .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Ghost Roaster"                            , Character.GhostRoaster         .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Cynder"                                   , Character.Cynder               .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Crystal Clear Cynder"                     , Character.Cynder               .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Metallic Purple Cynder"                   , Character.Cynder               .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Debug Minion"                             , Character.DebugMinionSSA       .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Anvil Rain"                               , Character.Anvil                .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Hidden Treasure"                          , Character.SecretStash          .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Healing Elixir"                           , Character.Regeneration         .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Ghost Swords"                             , Character.CrossedSwords        .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Time Twister"                             , Character.Hourglass            .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Sky-Iron Shield"                          , Character.Shield               .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Winged Boots"                             , Character.SpeedBoots           .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Sparx Dragonfly"                          , Character.Sparx                .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Dragon's Peak"                            , Character.Dragon               .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Empire of Ice"                            , Character.Ice                  .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Pirate Seas"                              , Character.Pirate               .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Darklight Crypt"                          , Character.Undead               .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Volcanic Vault"                           , Character.PVPUnlock            .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Legendary Bash"                           , Character.BashLegendary        .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Legendary Spyro"                          , Character.SpyroLegendary       .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Legendary Trigger Happy"                  , Character.TriggerHappyLegendary.id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Legendary Chop Chop"                      , Character.ChopChopLegendary    .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Terrabite"                                , Character.Terrabite            .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Gill Runt"                                , Character.GillRunt             .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Trigger Snappy"                           , Character.TriggerSnappy        .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Whisper Elf"                              , Character.WhisperElf           .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Template Template Bottom"                 , Character.TemplateSwapLegs     .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Template Template Top"                    , Character.TemplateSwapBody     .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Template Legacy"                          , Character.TemplateCharacterSSF .id, Game.SpyrosAdventure, Deco.Normal          ),
            ToyType("Whirlwind (Series 2)"                     , Character.Whirlwind            .id, Game.Giants         , Deco.Repose1         , repose = true),
            ToyType("Stone Whirlwind"                          , Character.Whirlwind            .id, Game.Giants         , Deco.StoneStatue     , repose = true),
            ToyType("Polar Whirlwind"                          , Character.Whirlwind            .id, Game.Giants         , Deco.Alternate       , repose = true, variant = true),
            ToyType("Sonic Boom (Series 2)"                    , Character.SonicBoom            .id, Game.Giants         , Deco.Repose1         , repose = true),
            ToyType("Glow-in-the-Dark Sonic Boom"              , Character.SonicBoom            .id, Game.Giants         , Deco.GlowDark        , repose = true),
            ToyType("Sparkle Sonic Boom"                       , Character.SonicBoom            .id, Game.Giants         , Deco.GlitterSpectrum , repose = true),
            ToyType("Lightning Rod (Series 2)"                 , Character.LightningRod         .id, Game.Giants         , Deco.Repose1         , repose = true),
            ToyType("Metallic Purple Lightning Rod"            , Character.LightningRod         .id, Game.Giants         , Deco.TreasureHunt2012, repose = true),
            ToyType("Bash (Series 2)"                          , Character.Bash                 .id, Game.Giants         , Deco.Repose1         , repose = true),
            ToyType("Terrafin (Series 2)"                      , Character.Terrafin             .id, Game.Giants         , Deco.Repose1         , repose = true),
            ToyType("Prism Break LightCore"                    , Character.PrismBreak           .id, Game.Giants         , Deco.LightDirect     , lightcore = true),
            ToyType("Employee Edition LightCore Prism Break"   , Character.PrismBreak           .id, Game.Giants         , Deco.LightDirect     , lightcore = true),
            ToyType("White Flocked Prism Break"                , Character.PrismBreak           .id, Game.Giants         , Deco.TreasureHunt2012, lightcore = true),
            ToyType("Prism Break (Series 2)"                   , Character.PrismBreak           .id, Game.Giants         , Deco.Repose1         , repose = true),
            ToyType("Eruptor LightCore"                        , Character.Eruptor              .id, Game.Giants         , Deco.LightDirect     , lightcore = true),
            ToyType("Eruptor (Series 2)"                       , Character.Eruptor              .id, Game.Giants         , Deco.Repose1         , repose = true),
            ToyType("White Flocked Eruptor"                    , Character.Eruptor              .id, Game.Giants         , Deco.TreasureHunt2012, repose = true),
            ToyType("Ignitor (Series 2)"                       , Character.Ignitor              .id, Game.Giants         , Deco.Repose1         , repose = true),
            ToyType("Legendary Ignitor"                        , Character.Ignitor              .id, Game.Giants         , Deco.Legendary       , repose = true, variant = true),
            ToyType("Flameslinger (Series 2)"                  , Character.Flameslinger         .id, Game.Giants         , Deco.Repose1         , repose = true),
            ToyType("Golden Flameslinger"                      , Character.Flameslinger         .id, Game.Giants         , Deco.Alternate       , repose = true),
            ToyType("Zap (Series 2)"                           , Character.Zap                  .id, Game.Giants         , Deco.Repose1         , repose = true),
            ToyType("Gill Grunt (Series 2)"                    , Character.GillGrunt            .id, Game.Giants         , Deco.Repose1         , repose = true),
            ToyType("Metallic Gill Grunt"                      , Character.GillGrunt            .id, Game.Giants         , Deco.ColorShift      , repose = true),
            ToyType("Slam Bam (Series 2)"                      , Character.SlamBam              .id, Game.Giants         , Deco.Repose1         , repose = true),
            ToyType("Legendary Slam Bam"                       , Character.SlamBam              .id, Game.Giants         , Deco.Legendary       , repose = true, variant = true),
            ToyType("Spyro (Series 2)"                         , Character.Spyro                .id, Game.Giants         , Deco.Repose1         , repose = true),
            ToyType("Double Trouble (Series 2)"                , Character.DoubleTrouble        .id, Game.Giants         , Deco.Repose1         , repose = true),
            ToyType("Double Trouble 1.5"                       , Character.DoubleTrouble        .id, Game.Giants         , Deco.Repose1         , repose = true),
            ToyType("Royal Double Trouble"                     , Character.DoubleTrouble        .id, Game.Giants         , Deco.Alternate       , repose = true, variant = true),
            ToyType("Trigger Happy (Series 2)"                 , Character.TriggerHappy         .id, Game.Giants         , Deco.Repose1         , repose = true),
            ToyType("Drobot LightCore"                         , Character.Drobot               .id, Game.Giants         , Deco.LightDirect     , lightcore = true),
            ToyType("Drobot (Series 2)"                        , Character.Drobot               .id, Game.Giants         , Deco.Repose1         , repose = true),
            ToyType("Drill Sergeant (Series 2)"                , Character.DrillSergeant        .id, Game.Giants         , Deco.Repose1         , repose = true),
            ToyType("Wrecking Ball (Series 2)"                 , Character.WreckingBall         .id, Game.Giants         , Deco.Repose1         , repose = true),
            ToyType("Metallic Purple Wrecking Ball"            , Character.WreckingBall         .id, Game.Giants         , Deco.TreasureHunt2012, repose = true),
            ToyType("Zook (Series 2)"                          , Character.Zook                 .id, Game.Giants         , Deco.Repose1         , repose = true),
            ToyType("Stone Zook"                               , Character.Zook                 .id, Game.Giants         , Deco.StoneStatue     , repose = true),
            ToyType("Stealth Elf (Series 2)"                   , Character.StealthElf           .id, Game.Giants         , Deco.Repose1         , repose = true),
            ToyType("Legendary Stealth Elf"                    , Character.StealthElf           .id, Game.Giants         , Deco.Legendary       , repose = true, variant = true),
            ToyType("Stump Smash (Series 2)"                   , Character.StumpSmash           .id, Game.Giants         , Deco.Repose1         , repose = true),
            ToyType("White Flocked Stump Smash"                , Character.StumpSmash           .id, Game.Giants         , Deco.TreasureHunt2012, repose = true),
            ToyType("Hex LightCore"                            , Character.Hex                  .id, Game.Giants         , Deco.LightDirect     , lightcore = true),
            ToyType("Hex (Series 2)"                           , Character.Hex                  .id, Game.Giants         , Deco.Repose1         , repose = true),
            ToyType("Chop Chop (Series 2)"                     , Character.ChopChop             .id, Game.Giants         , Deco.Repose1         , repose = true),
            ToyType("Metallic Blue Chop Chop"                  , Character.ChopChop             .id, Game.Giants         , Deco.Event           , repose = true),
            ToyType("Cynder (Series 2)"                        , Character.Cynder               .id, Game.Giants         , Deco.Repose1         , repose = true),
            ToyType("Glow-in-the-Dark Cynder"                  , Character.Cynder               .id, Game.Giants         , Deco.GlowDark        , repose = true),
            ToyType("Jet-Vac"                                  , Character.JetVac               .id, Game.Giants         , Deco.Normal          ),
            ToyType("Jet-Vac LightCore"                        , Character.JetVac               .id, Game.Giants         , Deco.LightDirect     , lightcore = true),
            ToyType("Legendary Jet-Vac"                        , Character.JetVac               .id, Game.Giants         , Deco.Legendary       , variant = true),
            ToyType("Swarm"                                    , Character.Swarm                .id, Game.Giants         , Deco.LightDirect     , lightcore = true),
            ToyType("Crusher"                                  , Character.Crusher              .id, Game.Giants         , Deco.LightDirect     , lightcore = true),
            ToyType("Granite Crusher"                          , Character.Crusher              .id, Game.Giants         , Deco.Alternate       , variant = true, lightcore = true),
            ToyType("Flashwing"                                , Character.Flashwing            .id, Game.Giants         , Deco.Normal          ),
            ToyType("Jade Flashwing"                           , Character.Flashwing            .id, Game.Giants         , Deco.Alternate       , variant = true),
            ToyType("Hot Head"                                 , Character.HotHead              .id, Game.Giants         , Deco.LightDirect     , lightcore = true),
            ToyType("Sparkle Hot Head"                         , Character.HotHead              .id, Game.Giants         , Deco.GlitterSpectrum , lightcore = true),
            ToyType("Hot Dog"                                  , Character.HotDog               .id, Game.Giants         , Deco.Normal          ),
            ToyType("Bronze Hot Dog"                           , Character.HotDog               .id, Game.Giants         , Deco.Halloween       ),
            ToyType("Molten Hot Dog"                           , Character.HotDog               .id, Game.Giants         , Deco.Alternate       , variant = true),
            ToyType("Chill"                                    , Character.Chill                .id, Game.Giants         , Deco.Normal          ),
            ToyType("Chill LightCore"                          , Character.Chill                .id, Game.Giants         , Deco.LightDirect     , lightcore = true),
            ToyType("Legendary LightCore Chill"                , Character.Chill                .id, Game.Giants         , Deco.Legendary       , variant = true, lightcore = true),
            ToyType("Thumpback"                                , Character.Thumpback            .id, Game.Giants         , Deco.LightDirect     , lightcore = true),
            ToyType("Pop Fizz"                                 , Character.PopFizz              .id, Game.Giants         , Deco.Normal          ),
            ToyType("Pop Fizz LightCore"                       , Character.PopFizz              .id, Game.Giants         , Deco.LightDirect     , lightcore = true),
            ToyType("Punch Pop Fizz"                           , Character.PopFizz              .id, Game.Giants         , Deco.Alternate       , variant = true),
            ToyType("Ninjini"                                  , Character.Ninjinni             .id, Game.Giants         , Deco.LightDirect     , lightcore = true),
            ToyType("Scarlet Ninjini"                          , Character.Ninjinni             .id, Game.Giants         , Deco.Alternate       , variant = true, lightcore = true),
            ToyType("Bouncer"                                  , Character.Bouncer              .id, Game.Giants         , Deco.LightDirect     , lightcore = true),
            ToyType("Legendary Bouncer"                        , Character.Bouncer              .id, Game.Giants         , Deco.Legendary       , variant = true, lightcore = true),
            ToyType("Sprocket"                                 , Character.Sprocket             .id, Game.Giants         , Deco.Normal          ),
            ToyType("Pearl Sprocket"                           , Character.Sprocket             .id, Game.Giants         , Deco.GlitterSpectrum ),
            ToyType("Tree Rex"                                 , Character.TreeRex              .id, Game.Giants         , Deco.LightDirect     , lightcore = true),
            ToyType("Gnarly Tree Rex"                          , Character.TreeRex              .id, Game.Giants         , Deco.Alternate       , variant = true, lightcore = true),
            ToyType("Shroomboom"                               , Character.Shroomboom           .id, Game.Giants         , Deco.Normal          ),
            ToyType("Metallic Green Shroomboom"                , Character.Shroomboom           .id, Game.Giants         , Deco.ColorShift      ),
            ToyType("Shroomboom LightCore"                     , Character.Shroomboom           .id, Game.Giants         , Deco.LightDirect     , lightcore = true),
            ToyType("Eye Brawl"                                , Character.EyeBrawl             .id, Game.Giants         , Deco.LightDirect     , lightcore = true),
            ToyType("Metallic Purple Eye-Brawl"                , Character.EyeBrawl             .id, Game.Giants         , Deco.TreasureHunt2012, lightcore = true),
            ToyType("Pumpkin Eye-Brawl"                        , Character.EyeBrawl             .id, Game.Giants         , Deco.Halloween       , lightcore = true),
            ToyType("Fright Rider"                             , Character.FrightRider          .id, Game.Giants         , Deco.Normal          ),
            ToyType("Glow-in-the-Dark Fright Rider"            , Character.FrightRider          .id, Game.Giants         , Deco.GlowDark        ),
            ToyType("Halloween Fright Rider"                   , Character.FrightRider          .id, Game.Giants         , Deco.Halloween       ),
            ToyType("Platinum Treasure Chest"                  , Character.SecretStash          .id, Game.Giants         , Deco.Normal          ),
            ToyType("Dragonfire Cannon"                        , Character.Cannon               .id, Game.Giants         , Deco.LightDirect     , lightcore = true),
            ToyType("Golden Dragonfire Cannon"                 , Character.Cannon               .id, Game.Giants         , Deco.Alternate       , variant = true, lightcore = true),
            ToyType("Scorpion Striker Catapult"                , Character.Catapult             .id, Game.Giants         , Deco.LightDirect     , lightcore = true),
            ToyType("Barkley"                                  , Character.Barkely              .id, Game.Giants         , Deco.Normal          ),
            ToyType("Thumpling"                                , Character.Thumpling            .id, Game.Giants         , Deco.Normal          ),
            ToyType("Mini Jini"                                , Character.MiniJini             .id, Game.Giants         , Deco.Normal          ),
            ToyType("Eye Small"                                , Character.EyeSmall             .id, Game.Giants         , Deco.Normal          ),
            ToyType("Debug Minion"                             , Character.DebugMinionSG        .id, Game.Giants         , Deco.Normal          ),
            ToyType("Horn Blast Whirlwind (Series 3)"          , Character.Whirlwind            .id, Game.SwapForce      , Deco.Repose2         , repose = true),
            ToyType("Warnado LightCore"                        , Character.Warnado              .id, Game.SwapForce      , Deco.LightDirect     , lightcore = true),
            ToyType("Knockout Terrafin (Series 3)"             , Character.Terrafin             .id, Game.SwapForce      , Deco.Repose2         , repose = true),
            ToyType("Hyper Beam Prism Break (Series 3)"        , Character.PrismBreak           .id, Game.SwapForce      , Deco.Repose2         , repose = true),
            ToyType("Lava Barf Eruptor (Series 3)"             , Character.Eruptor              .id, Game.SwapForce      , Deco.Repose2         , repose = true),
            ToyType("Volcanic Eruptor"                         , Character.Eruptor              .id, Game.SwapForce      , Deco.Alternate       , repose = true, variant = true),
            ToyType("Wham-Shell LightCore"                     , Character.WhamShell            .id, Game.SwapForce      , Deco.LightDirect     , lightcore = true),
            ToyType("Anchors Away Gill Grunt (Series 3)"       , Character.GillGrunt            .id, Game.SwapForce      , Deco.Repose2         , repose = true),
            ToyType("Mega Ram Spyro (Series 3)"                , Character.Spyro                .id, Game.SwapForce      , Deco.Repose2         , repose = true),
            ToyType("Mega Ram Dark Spyro"                      , Character.Spyro                .id, Game.SwapForce      , Deco.Alternate       , repose = true, variant = true),
            ToyType("Big Bang Trigger Happy (Series 3)"        , Character.TriggerHappy         .id, Game.SwapForce      , Deco.Repose2         , repose = true),
            ToyType("Springtime Trigger Happy"                 , Character.TriggerHappy         .id, Game.SwapForce      , Deco.Alternate       , repose = true, variant = true),
            ToyType("Flocked Springtime Trigger Happy"         , Character.TriggerHappy         .id, Game.SwapForce      , Deco.Alternate       , repose = true, variant = true),
            ToyType("Thorn Horn Camo (Series 2)"               , Character.Camo                 .id, Game.SwapForce      , Deco.Repose2         , repose = true),
            ToyType("Ninja Stealth Elf (Series 3)"             , Character.StealthElf           .id, Game.SwapForce      , Deco.Repose2         , repose = true),
            ToyType("Dark Stealth Elf"                         , Character.StealthElf           .id, Game.SwapForce      , Deco.Alternate       , repose = true, variant = true),
            ToyType("Twin Blade Chop Chop (Series 3)"          , Character.ChopChop             .id, Game.SwapForce      , Deco.Repose2         , repose = true),
            ToyType("Green Chop Chop"                          , Character.ChopChop             .id, Game.SwapForce      , Deco.TreasureHunt2013, repose = true),
            ToyType("Phantom Cynder (Series 3)"                , Character.Cynder               .id, Game.SwapForce      , Deco.Repose2         , repose = true),
            ToyType("Turbo Jet-Vac (Series 2)"                 , Character.JetVac               .id, Game.SwapForce      , Deco.Repose2         , repose = true),
            ToyType("Flashwing LightCore"                      , Character.Flashwing            .id, Game.SwapForce      , Deco.LightDirect     , lightcore = true),
            ToyType("Fire Bone Hot Dog (Series 2)"             , Character.HotDog               .id, Game.SwapForce      , Deco.Repose2         , repose = true),
            ToyType("Red Flame Frito-Lay Fire Bone Hot Dog"    , Character.HotDog               .id, Game.SwapForce      , Deco.FritoLay        , repose = true),
            ToyType("Green Flame Frito-Lay Fire Bone Hot Dog"  , Character.HotDog               .id, Game.SwapForce      , Deco.Deco27          , repose = true),
            ToyType("Purple Flame Frito-Lay Fire Bone Hot Dog" , Character.HotDog               .id, Game.SwapForce      , Deco.Deco28          , repose = true),
            ToyType("Blizzard Chill (Series 2)"                , Character.Chill                .id, Game.SwapForce      , Deco.Repose2         , repose = true),
            ToyType("Super Gulp Pop Fizz (Series 2)"           , Character.PopFizz              .id, Game.SwapForce      , Deco.Repose2         , repose = true),
            ToyType("Heavy Duty Sprocket (Series 2)"           , Character.Sprocket             .id, Game.SwapForce      , Deco.Repose2         , repose = true),
            ToyType("Heavy Metal Sprocket"                     , Character.Sprocket             .id, Game.SwapForce      , Deco.BestBuy         , repose = true),
            ToyType("Boom Jet Bottom"                          , Character.AviatorLegs          .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Free Ranger Bottom"                       , Character.StormBirdLegs        .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Legendary Free Ranger Bottom"             , Character.StormBirdLegs        .id, Game.SwapForce      , Deco.Legendary       , variant = true),
            ToyType("Rubble Rouser Bottom"                     , Character.MinerLegs            .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Doom Stone Bottom"                        , Character.StatueLegs           .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Gold & Bronze Doom Stone Bottom"          , Character.StatueLegs           .id, Game.SwapForce      , Deco.TreasureHunt2013),
            ToyType("Blast Zone Bottom"                        , Character.FireKnightLegs       .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Dark Blast Zone Bottom"                   , Character.FireKnightLegs       .id, Game.SwapForce      , Deco.Alternate       , variant = true),
            ToyType("Fire Kraken Bottom"                       , Character.FireworksLegs        .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Gold Fire Kraken Bottom"                  , Character.FireworksLegs        .id, Game.SwapForce      , Deco.Event           ),
            ToyType("Jade Fire Kraken Bottom"                  , Character.FireworksLegs        .id, Game.SwapForce      , Deco.Alternate       , variant = true),
            ToyType("Stink Bomb Bottom"                        , Character.NinjaLegs            .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Silver & Gold Stink Bomb Bottom"          , Character.NinjaLegs            .id, Game.SwapForce      , Deco.TreasureHunt2013),
            ToyType("Grilla Drilla Bottom"                     , Character.GorillaLegs          .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Hoot Loop Bottom"                         , Character.FortuneLegs          .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Enchanted Hoot Loop Bottom"               , Character.FortuneLegs          .id, Game.SwapForce      , Deco.Alternate       , variant = true),
            ToyType("Trap Shadow Bottom"                       , Character.PantherLegs          .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Bronze & Silver Trap Shadow Bottom"       , Character.PantherLegs          .id, Game.SwapForce      , Deco.TreasureHunt2013),
            ToyType("Magna Charge Bottom"                      , Character.MagnetLegs           .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Nitro Magna Charge Bottom"                , Character.MagnetLegs           .id, Game.SwapForce      , Deco.Alternate       , variant = true),
            ToyType("Spy Rise Bottom"                          , Character.SpyderLegs           .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Night Shift Bottom"                       , Character.VampireLegs          .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Legendary Night Shift Bottom"             , Character.VampireLegs          .id, Game.SwapForce      , Deco.Legendary       , variant = true),
            ToyType("Rattle Shake Bottom"                      , Character.CowboyLegs           .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Quick Draw Rattle Shake Bottom"           , Character.CowboyLegs           .id, Game.SwapForce      , Deco.Alternate       , variant = true),
            ToyType("Freeze Blade Bottom"                      , Character.FreezeLegs           .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Nitro Freeze Blade Bottom"                , Character.FreezeLegs           .id, Game.SwapForce      , Deco.Alternate       , variant = true),
            ToyType("Wash Buckler Bottom"                      , Character.PirateLegs           .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Gold Wash Buckler Bottom"                 , Character.PirateLegs           .id, Game.SwapForce      , Deco.WiiU            ),
            ToyType("Dark Wash Buckler Bottom"                 , Character.PirateLegs           .id, Game.SwapForce      , Deco.Alternate       , variant = true),
            ToyType("Boom Jet Top"                             , Character.AviatorBody          .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Free Ranger Top"                          , Character.StormBirdBody        .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Legendary Free Ranger Top"                , Character.StormBirdBody        .id, Game.SwapForce      , Deco.Legendary       , variant = true),
            ToyType("Rubble Rouser Top"                        , Character.MinerBody            .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Doom Stone Top"                           , Character.StatueBody           .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Gold & Bronze Doom Stone Top"             , Character.StatueBody           .id, Game.SwapForce      , Deco.TreasureHunt2013),
            ToyType("Blast Zone Top"                           , Character.FireKnightBody       .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Dark Blast Zone Top"                      , Character.FireKnightBody       .id, Game.SwapForce      , Deco.Alternate       , variant = true),
            ToyType("Fire Kraken Top"                          , Character.FireworksBody        .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Gold Fire Kraken Top"                     , Character.FireworksBody        .id, Game.SwapForce      , Deco.Event           ),
            ToyType("Jade Fire Kraken Top"                     , Character.FireworksBody        .id, Game.SwapForce      , Deco.Alternate       , variant = true),
            ToyType("Stink Bomb Top"                           , Character.NinjaBody            .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Silver & Gold Stink Bomb Top"             , Character.NinjaBody            .id, Game.SwapForce      , Deco.TreasureHunt2013),
            ToyType("Grilla Drilla Top"                        , Character.GorillaBody          .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Hoot Loop Top"                            , Character.FortuneBody          .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Enchanted Hoot Loop Top"                  , Character.FortuneBody          .id, Game.SwapForce      , Deco.Alternate       , variant = true),
            ToyType("Trap Shadow Top"                          , Character.PantherBody          .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Bronze & Silver Trap Shadow Top"          , Character.PantherBody          .id, Game.SwapForce      , Deco.TreasureHunt2013),
            ToyType("Magna Charge Top"                         , Character.MagnetBody           .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Nitro Magna Charge Top"                   , Character.MagnetBody           .id, Game.SwapForce      , Deco.Alternate       , variant = true),
            ToyType("Spy Rise Top"                             , Character.SpyderBody           .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Night Shift Top"                          , Character.VampireBody          .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Legendary Night Shift Top"                , Character.VampireBody          .id, Game.SwapForce      , Deco.Legendary       , variant = true),
            ToyType("Rattle Shake Top"                         , Character.CowboyBody           .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Quick Draw Rattle Shake Top"              , Character.CowboyBody           .id, Game.SwapForce      , Deco.Alternate       , variant = true),
            ToyType("Freeze Blade Top"                         , Character.FreezeBody           .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Nitro Freeze Blade Top"                   , Character.FreezeBody           .id, Game.SwapForce      , Deco.Alternate       , variant = true),
            ToyType("Wash Buckler Top"                         , Character.PirateBody           .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Gold Wash Buckler Top"                    , Character.PirateBody           .id, Game.SwapForce      , Deco.WiiU            ),
            ToyType("Dark Wash Buckler Top"                    , Character.PirateBody           .id, Game.SwapForce      , Deco.Alternate       , variant = true),
            ToyType("Scratch"                                  , Character.CatGryphon           .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Pop Thorn"                                , Character.PuffDragon           .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Slobber Tooth"                            , Character.LockJaw              .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Dark Slobber Tooth"                       , Character.LockJaw              .id, Game.SwapForce      , Deco.Alternate       , variant = true),
            ToyType("Scorp"                                    , Character.Scorpion             .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Green Scorp"                              , Character.Scorpion             .id, Game.SwapForce      , Deco.TreasureHunt2013),
            ToyType("Fryno"                                    , Character.Fyno                 .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Smolderdash"                              , Character.SunGirl              .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Smolderdash LightCore"                    , Character.SunGirl              .id, Game.SwapForce      , Deco.LightDirect     , lightcore = true),
            ToyType("Employee Edition LightCore Smolderdash"   , Character.SunGirl              .id, Game.SwapForce      , Deco.BestBuy         , lightcore = true),
            ToyType("Bumble Blast"                             , Character.BeeTree              .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Bumble Blast LightCore"                   , Character.BeeTree              .id, Game.SwapForce      , Deco.LightDirect     , lightcore = true),
            ToyType("Jolly Bumble Blast"                       , Character.BeeTree              .id, Game.SwapForce      , Deco.Alternate       , variant = true),
            ToyType("Zoo Lou"                                  , Character.Shaman               .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Legendary Zoo Lou"                        , Character.Shaman               .id, Game.SwapForce      , Deco.Legendary       , variant = true),
            ToyType("Dune Bug"                                 , Character.DuneBug              .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Metallic Red Dune Bug"                    , Character.DuneBug              .id, Game.SwapForce      , Deco.Event           ),
            ToyType("Star Strike"                              , Character.FanGirl              .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Star Strike LightCore"                    , Character.FanGirl              .id, Game.SwapForce      , Deco.LightDirect     , lightcore = true),
            ToyType("Enchanted LightCore Star Strike"          , Character.FanGirl              .id, Game.SwapForce      , Deco.Alternate       , variant = true, lightcore = true),
            ToyType("Countdown"                                , Character.DaBomb               .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Countdown LightCore"                      , Character.DaBomb               .id, Game.SwapForce      , Deco.LightDirect     , lightcore = true),
            ToyType("Kickoff Countdown"                        , Character.DaBomb               .id, Game.SwapForce      , Deco.Alternate       , variant = true),
            ToyType("Wind-Up"                                  , Character.WindUp               .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("VVind-Up"                                 , Character.WindUp               .id, Game.SwapForce      , Deco.Event           , variant = true),
            ToyType("Roller Brawl"                             , Character.TopsyDerby           .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Grim Creeper"                             , Character.Reaper               .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Grim Creeper LightCore"                   , Character.Reaper               .id, Game.SwapForce      , Deco.LightDirect     , lightcore = true),
            ToyType("Legendary LightCore Grim Creeper"         , Character.Reaper               .id, Game.SwapForce      , Deco.Legendary       , variant = true, lightcore = true),
            ToyType("Rip Tide"                                 , Character.Swordfish            .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Green Rip Tide"                           , Character.Swordfish            .id, Game.SwapForce      , Deco.TreasureHunt2013),
            ToyType("Punk Shock"                               , Character.EelGirl              .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Battle Hammer"                            , Character.Hammer               .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Sky Diamond"                              , Character.Diamonds             .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Platinum Sheep"                           , Character.GoldenSheep          .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Groove Machine"                           , Character.Gramophone           .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("UFO Hat"                                  , Character.HatPromo             .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Sheep Wreck Island"                       , Character.SheepWreckIsland     .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Tower of Time"                            , Character.ClockTower           .id, Game.SwapForce      , Deco.Normal          ),
            ToyType("Fiery Forge"                              , Character.BattleArena1         .id, Game.SwapForce      , Deco.LightDirect     , lightcore = true),
            ToyType("Arkeyan Crossbow"                         , Character.BattleArena2         .id, Game.SwapForce      , Deco.LightDirect     , lightcore = true),
            ToyType("Eon's Elite Whirlwind"                    , Character.Whirlwind            .id, Game.TrapTeam       , Deco.Premium         , repose = true),
            ToyType("Eon's Elite Terrafin"                     , Character.Terrafin             .id, Game.TrapTeam       , Deco.Premium         , repose = true),
            ToyType("Eon's Elite Eruptor"                      , Character.Eruptor              .id, Game.TrapTeam       , Deco.Premium         , repose = true),
            ToyType("Tidal Wave Gill Grunt (Series 4)"         , Character.GillGrunt            .id, Game.TrapTeam       , Deco.Repose3         , repose = true),
            ToyType("Eon's Elite Gill Grunt"                   , Character.GillGrunt            .id, Game.TrapTeam       , Deco.Premium         , repose = true),
            ToyType("Eon's Elite Spyro"                        , Character.Spyro                .id, Game.TrapTeam       , Deco.Premium         , repose = true),
            ToyType("Eon's Elite Trigger Happy"                , Character.TriggerHappy         .id, Game.TrapTeam       , Deco.Premium         , repose = true),
            ToyType("Eon's Elite Stealth Elf"                  , Character.StealthElf           .id, Game.TrapTeam       , Deco.Premium         , repose = true),
            ToyType("Eon's Elite Chop Chop"                    , Character.ChopChop             .id, Game.TrapTeam       , Deco.Premium         , repose = true),
            ToyType("Full Blast Jet-Vac (Series 3)"            , Character.JetVac               .id, Game.TrapTeam       , Deco.Repose2         , repose = true),
            ToyType("Fizzy Frenzy Pop Fizz (Series 3)"         , Character.PopFizz              .id, Game.TrapTeam       , Deco.Repose2         , repose = true),
            ToyType("Love Potion Pop Fizz"                     , Character.PopFizz              .id, Game.TrapTeam       , Deco.Alternate       , repose = true, variant = true),
            ToyType("Sure Shot Shroomboom (Series 2)"          , Character.Shroomboom           .id, Game.TrapTeam       , Deco.Repose1         , repose = true),
            ToyType("Magic Log Holder (Biter's Bane)"          , Character.MagicTrap            .id, Game.TrapTeam       , Deco.Alternate       ),
            ToyType("Magic Skull (Sorcerous Skull)"            , Character.MagicTrap            .id, Game.TrapTeam       , Deco.LightEnhanced   ),
            ToyType("Magic Axe (Axe of Illusion)"              , Character.MagicTrap            .id, Game.TrapTeam       , Deco.Repose5         ),
            ToyType("Bomb Shell"                               , Character.MagicTrap            .id, Game.TrapTeam       , Deco.Repose5         ),
            ToyType("Magic Hourglass (Arcane Hourglass)"       , Character.MagicTrap            .id, Game.TrapTeam       , Deco.Winter          ),
            ToyType("Rage Mage"                                , Character.MagicTrap            .id, Game.TrapTeam       , Deco.Winter          ),
            ToyType("Magic Totem (Spell Slapper)"              , Character.MagicTrap            .id, Game.TrapTeam       , Deco.StoneStatue     ),
            ToyType("Pain-Yatta"                               , Character.MagicTrap            .id, Game.TrapTeam       , Deco.StoneStatue     ),
            ToyType("Magic Rocket (Rune Rocket)"               , Character.MagicTrap            .id, Game.TrapTeam       , Deco.Halloween       ),
            ToyType("Water Tiki (Tidal Tiki)"                  , Character.WaterTrap            .id, Game.TrapTeam       , Deco.Repose1         ),
            ToyType("Water Log Holder (Wet Walter)"            , Character.WaterTrap            .id, Game.TrapTeam       , Deco.Alternate       ),
            ToyType("Brawl and Chain"                          , Character.WaterTrap            .id, Game.TrapTeam       , Deco.Alternate       ),
            ToyType("Outlaw Brawl and Chain"                   , Character.WaterTrap            .id, Game.TrapTeam       , Deco.Alternate       ),
            ToyType("Water Jughead (Flood Flask)"              , Character.WaterTrap            .id, Game.TrapTeam       , Deco.LightDirect     ),
            ToyType("Water Angel (Soaking Staff)"              , Character.WaterTrap            .id, Game.TrapTeam       , Deco.LightStored     ),
            ToyType("Chill Bill"                               , Character.WaterTrap            .id, Game.TrapTeam       , Deco.LightStored     ),
            ToyType("Cross Crow"                               , Character.WaterTrap            .id, Game.TrapTeam       , Deco.LightStored     ),
            ToyType("Gulper (Doom Raider)"                     , Character.WaterTrap            .id, Game.TrapTeam       , Deco.LightStored     ),
            ToyType("Slobber Trap"                             , Character.WaterTrap            .id, Game.TrapTeam       , Deco.LightStored     ),
            ToyType("Threatpack"                               , Character.WaterTrap            .id, Game.TrapTeam       , Deco.LightStored     ),
            ToyType("Water Axe (Aqua Axe)"                     , Character.WaterTrap            .id, Game.TrapTeam       , Deco.Repose5         ),
            ToyType("Water Flying Helmet (Frost Helm)"         , Character.WaterTrap            .id, Game.TrapTeam       , Deco.TreasureHunt2013),
            ToyType("Legendary Flood Flask (Water Jughead)"    , Character.WaterTrap            .id, Game.TrapTeam       , Deco.LightDirect     , variant = true),
            ToyType("Air Toucan (Breezy Bird)"                 , Character.AirTrap              .id, Game.TrapTeam       , Deco.Legendary       ),
            ToyType("Air Jughead (Drafty Decanter)"            , Character.AirTrap              .id, Game.TrapTeam       , Deco.LightDirect     ),
            ToyType("Air Hourglass (Tempest Timer)"            , Character.AirTrap              .id, Game.TrapTeam       , Deco.Winter          ),
            ToyType("Air Snake (Cloudy Cobra)"                 , Character.AirTrap              .id, Game.TrapTeam       , Deco.Premium         ),
            ToyType("Buzzer Beak"                              , Character.AirTrap              .id, Game.TrapTeam       , Deco.Premium         ),
            ToyType("Krankenstein"                             , Character.AirTrap              .id, Game.TrapTeam       , Deco.Premium         ),
            ToyType("Air Screamer (Storm Warning)"             , Character.AirTrap              .id, Game.TrapTeam       , Deco.GlowDark        ),
            ToyType("Bad Juju"                                 , Character.AirTrap              .id, Game.TrapTeam       , Deco.GlowDark        ),
            ToyType("Dreamcatcher (Doom Raider)"               , Character.AirTrap              .id, Game.TrapTeam       , Deco.GlowDark        ),
            ToyType("Air Sword (Cyclone Sabre)"                , Character.AirTrap              .id, Game.TrapTeam       , Deco.WiiU            ),
            ToyType("Undead Orb (Spirit Sphere)"               , Character.DeathTrap            .id, Game.TrapTeam       , Deco.Event           ),
            ToyType("Undead Skull (Spectral Skull)"            , Character.DeathTrap            .id, Game.TrapTeam       , Deco.LightEnhanced   ),
            ToyType("Undead Axe (Haunted Hatchet)"             , Character.DeathTrap            .id, Game.TrapTeam       , Deco.Repose5         ),
            ToyType("Undead Hand (Grim Gripper)"               , Character.DeathTrap            .id, Game.TrapTeam       , Deco.Valentines      ),
            ToyType("Bone Chompy"                              , Character.DeathTrap            .id, Game.TrapTeam       , Deco.Valentines      ),
            ToyType("Hood Sickle"                              , Character.DeathTrap            .id, Game.TrapTeam       , Deco.Valentines      ),
            ToyType("Masker Mind"                              , Character.DeathTrap            .id, Game.TrapTeam       , Deco.Valentines      ),
            ToyType("Wolfgang (Doom Raider)"                   , Character.DeathTrap            .id, Game.TrapTeam       , Deco.Valentines      ),
            ToyType("Undead Snake (Spooky Snake)"              , Character.DeathTrap            .id, Game.TrapTeam       , Deco.Premium         ),
            ToyType("Undead Captain's Hat (Dream Piercer)"     , Character.DeathTrap            .id, Game.TrapTeam       , Deco.ColorShift      ),
            ToyType("Legendary Spirit Sphere (Undead Orb)"     , Character.DeathTrap            .id, Game.TrapTeam       , Deco.Event           , variant = true),
            ToyType("Legendary Spectral Skull (Undead Skull)"  , Character.DeathTrap            .id, Game.TrapTeam       , Deco.LightEnhanced   , variant = true),
            ToyType("Tech Tiki (Tech Totem)"                   , Character.TechTrap             .id, Game.TrapTeam       , Deco.Repose1         ),
            ToyType("Brawlrus"                                 , Character.TechTrap             .id, Game.TrapTeam       , Deco.Repose1         ),
            ToyType("Bruiser Cruiser"                          , Character.TechTrap             .id, Game.TrapTeam       , Deco.Repose1         ),
            ToyType("Dr. Krankcase (Doom Raider)"              , Character.TechTrap             .id, Game.TrapTeam       , Deco.Repose1         ),
            ToyType("Tech Angel (Automatic Angel)"             , Character.TechTrap             .id, Game.TrapTeam       , Deco.LightStored     ),
            ToyType("Shrednaught"                              , Character.TechTrap             .id, Game.TrapTeam       , Deco.LightStored     ),
            ToyType("Tech Scepter (Factory Flower)"            , Character.TechTrap             .id, Game.TrapTeam       , Deco.Repose3         ),
            ToyType("Trolling Thunder"                         , Character.TechTrap             .id, Game.TrapTeam       , Deco.Repose3         ),
            ToyType("Tech Hand (Grabbing Gadget)"              , Character.TechTrap             .id, Game.TrapTeam       , Deco.Valentines      ),
            ToyType("Tech Flying Helmet (Makers Mana)"         , Character.TechTrap             .id, Game.TrapTeam       , Deco.TreasureHunt2013),
            ToyType("Mab Lobs"                                 , Character.TechTrap             .id, Game.TrapTeam       , Deco.TreasureHunt2013),
            ToyType("Steampunk Shrednaught"                    , Character.TechTrap             .id, Game.TrapTeam       , Deco.TreasureHunt2013),
            ToyType("Tech Handstand (Topsy Techy)"             , Character.TechTrap             .id, Game.TrapTeam       , Deco.FritoLay        ),
            ToyType("Fire Torch (Eternal Flame)"               , Character.FireTrap             .id, Game.TrapTeam       , Deco.Repose2         ),
            ToyType("Fire Scepter (Fire Flower)"               , Character.FireTrap             .id, Game.TrapTeam       , Deco.Repose3         ),
            ToyType("Chef Pepper Jack (Doom Raider)"           , Character.FireTrap             .id, Game.TrapTeam       , Deco.Repose3         ),
            ToyType("Smoke Scream"                             , Character.FireTrap             .id, Game.TrapTeam       , Deco.Repose3         ),
            ToyType("Fire Screamer (Scorching Stopper)"        , Character.FireTrap             .id, Game.TrapTeam       , Deco.GlowDark        ),
            ToyType("Scrap Shooter"                            , Character.FireTrap             .id, Game.TrapTeam       , Deco.GlowDark        ),
            ToyType("Fire Totem (Searing Spinner)"             , Character.FireTrap             .id, Game.TrapTeam       , Deco.StoneStatue     ),
            ToyType("Fire Captain's Hat (Spark Spear)"         , Character.FireTrap             .id, Game.TrapTeam       , Deco.ColorShift      ),
            ToyType("Fire Yawn (Blazing Belch)"                , Character.FireTrap             .id, Game.TrapTeam       , Deco.Deco27          ),
            ToyType("Grinnade"                                 , Character.FireTrap             .id, Game.TrapTeam       , Deco.Deco27          ),
            ToyType("Earth Toucan (Rock Hawk)"                 , Character.EarthTrap            .id, Game.TrapTeam       , Deco.Legendary       ),
            ToyType("Earth Orb (Banded Boulder)"               , Character.EarthTrap            .id, Game.TrapTeam       , Deco.Event           ),
            ToyType("Earth Hammer (Slag Hammer)"               , Character.EarthTrap            .id, Game.TrapTeam       , Deco.Repose4         ),
            ToyType("Earth Hourglass (Dust of Time)"           , Character.EarthTrap            .id, Game.TrapTeam       , Deco.Winter          ),
            ToyType("Chomp Chest"                              , Character.EarthTrap            .id, Game.TrapTeam       , Deco.Winter          ),
            ToyType("Golden Queen (Doom Raider)"               , Character.EarthTrap            .id, Game.TrapTeam       , Deco.Winter          ),
            ToyType("Grave Clobber"                            , Character.EarthTrap            .id, Game.TrapTeam       , Deco.Winter          ),
            ToyType("Earth Totem (Spinning Sandstorm)"         , Character.EarthTrap            .id, Game.TrapTeam       , Deco.StoneStatue     ),
            ToyType("Red Hot Tussle Sprout"                    , Character.EarthTrap            .id, Game.TrapTeam       , Deco.StoneStatue     ),
            ToyType("Earth Handstand (Rubble Trouble)"         , Character.EarthTrap            .id, Game.TrapTeam       , Deco.FritoLay        ),
            ToyType("Easter Bunny Earth Trap"                  , Character.EarthTrap            .id, Game.TrapTeam       , Deco.FritoLay        ),
            ToyType("Tussle Sprout"                            , Character.EarthTrap            .id, Game.TrapTeam       , Deco.FritoLay        ),
            ToyType("Life Toucan (Oak Eagle)"                  , Character.LifeTrap             .id, Game.TrapTeam       , Deco.Repose1         ),
            ToyType("Cuckoo Clocker"                           , Character.LifeTrap             .id, Game.TrapTeam       , Deco.Legendary       ),
            ToyType("Sheep Creep"                              , Character.LifeTrap             .id, Game.TrapTeam       , Deco.Legendary       ),
            ToyType("Shield Shredder"                          , Character.LifeTrap             .id, Game.TrapTeam       , Deco.Legendary       ),
            ToyType("Steamed Broccoli Guy"                     , Character.LifeTrap             .id, Game.TrapTeam       , Deco.Legendary       ),
            ToyType("Life Torch (Emerald Energy)"              , Character.LifeTrap             .id, Game.TrapTeam       , Deco.Repose2         ),
            ToyType("Chompy Mage (Doom Raider)"                , Character.LifeTrap             .id, Game.TrapTeam       , Deco.Repose2         ),
            ToyType("Riot Shield Shredder"                     , Character.LifeTrap             .id, Game.TrapTeam       , Deco.Repose2         ),
            ToyType("Life Hammer (Weed Whacker)"               , Character.LifeTrap             .id, Game.TrapTeam       , Deco.Repose4         ),
            ToyType("Broccoli Guy"                             , Character.LifeTrap             .id, Game.TrapTeam       , Deco.Repose4         ),
            ToyType("Life Snake (Seed Serpent)"                , Character.LifeTrap             .id, Game.TrapTeam       , Deco.Premium         ),
            ToyType("Chompy"                                   , Character.LifeTrap             .id, Game.TrapTeam       , Deco.Premium         ),
            ToyType("Life Sword (Jade Blade)"                  , Character.LifeTrap             .id, Game.TrapTeam       , Deco.WiiU            ),
            ToyType("Life Yawn (Shrub Shrieker)"               , Character.LifeTrap             .id, Game.TrapTeam       , Deco.Deco27          ),
            ToyType("Dark Spider (Shadow Spider)"              , Character.DarkTrap             .id, Game.TrapTeam       , Deco.TreasureHunt2012),
            ToyType("Tae Kwon Crow"                            , Character.DarkTrap             .id, Game.TrapTeam       , Deco.TreasureHunt2012),
            ToyType("Dark Sword (Dark Dagger)"                 , Character.DarkTrap             .id, Game.TrapTeam       , Deco.WiiU            ),
            ToyType("Eye Scream"                               , Character.DarkTrap             .id, Game.TrapTeam       , Deco.WiiU            ),
            ToyType("Fisticuffs"                               , Character.DarkTrap             .id, Game.TrapTeam       , Deco.WiiU            ),
            ToyType("Nightshade (Doom Raider)"                 , Character.DarkTrap             .id, Game.TrapTeam       , Deco.WiiU            ),
            ToyType("Dark Handstand (Ghastly Grimace)"         , Character.DarkTrap             .id, Game.TrapTeam       , Deco.FritoLay        ),
            ToyType("Light Owl (Heavenly Hawk)"                , Character.LightTrap            .id, Game.TrapTeam       , Deco.Virtual         ),
            ToyType("Blaster-Tron"                             , Character.LightTrap            .id, Game.TrapTeam       , Deco.Virtual         ),
            ToyType("Luminous (Doom Raider)"                   , Character.LightTrap            .id, Game.TrapTeam       , Deco.Virtual         ),
            ToyType("Light Rocket (Shining Ship)"              , Character.LightTrap            .id, Game.TrapTeam       , Deco.Halloween       ),
            ToyType("Rebel Lob Goblin"                         , Character.LightTrap            .id, Game.TrapTeam       , Deco.Halloween       ),
            ToyType("Light Yawn (Beam Scream)"                 , Character.LightTrap            .id, Game.TrapTeam       , Deco.Deco27          ),
            ToyType("Eye Five"                                 , Character.LightTrap            .id, Game.TrapTeam       , Deco.Deco27          ),
            ToyType("Lob Goblin"                               , Character.LightTrap            .id, Game.TrapTeam       , Deco.Deco27          ),
            ToyType("Kaos Trap"                                , Character.KaosTrap             .id, Game.TrapTeam       , Deco.TreasureHunt2015),
            ToyType("Kaos (Doom Raider)"                       , Character.KaosTrap             .id, Game.TrapTeam       , Deco.TreasureHunt2015),
            ToyType("Ultimate Kaos Trap (Dark Edition Variant)", Character.KaosTrap             .id, Game.TrapTeam       , Deco.Mobile          , variant = true, supercharger = true),
            ToyType("Hand of Fate"                             , Character.HandOfFate           .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Legendary Hand of Fate"                   , Character.HandOfFate           .id, Game.TrapTeam       , Deco.Legendary       , variant = true),
            ToyType("Piggy Bank"                               , Character.PiggyBank            .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Rocket Ram"                               , Character.RocketRam            .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Tiki Speaky"                              , Character.TikiSpeaky           .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Mirror of Mystery"                        , Character.MirrorOfMystery      .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Nightmare Express"                        , Character.NightmareExpress     .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Sunscraper Spire"                         , Character.SunscraperSpire      .id, Game.TrapTeam       , Deco.LightDirect     , lightcore = true),
            ToyType("Midnight Museum"                          , Character.MidnightMuseum       .id, Game.TrapTeam       , Deco.LightDirect     , lightcore = true),
            ToyType("Gusto"                                    , Character.Gusto                .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Thunderbolt"                              , Character.Thunderbolt          .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Clear Thunderbolt"                        , Character.Thunderbolt          .id, Game.TrapTeam       , Deco.TreasureHunt2014),
            ToyType("Fling Kong"                               , Character.FlingKong            .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Blades"                                   , Character.Blades               .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Legendary Blades"                         , Character.Blades               .id, Game.TrapTeam       , Deco.Legendary       , variant = true),
            ToyType("Wallop"                                   , Character.Wallop               .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Head Rush"                                , Character.HeadRush             .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Nitro Head Rush"                          , Character.HeadRush             .id, Game.TrapTeam       , Deco.Alternate       , variant = true),
            ToyType("Fist Bump"                                , Character.FistBump             .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Rocky Roll"                               , Character.RockyRoll            .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Wildfire"                                 , Character.WildFire             .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Dark Wildfire"                            , Character.WildFire             .id, Game.TrapTeam       , Deco.Alternate       , variant = true),
            ToyType("Ka-Boom"                                  , Character.KaBoom               .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Trail Blazer"                             , Character.TrailBlazer          .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Torch"                                    , Character.Torch                .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Snap Shot"                                , Character.SnapShot             .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Dark Snap Shot"                           , Character.SnapShot             .id, Game.TrapTeam       , Deco.Alternate       , variant = true),
            ToyType("Lob-Star"                                 , Character.LobStar              .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Winterfest Lob-Star"                      , Character.LobStar              .id, Game.TrapTeam       , Deco.Alternate       , variant = true),
            ToyType("Flip Wreck"                               , Character.FlipWreck            .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Echo"                                     , Character.Echo                 .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Blastermind"                              , Character.Blastermind          .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Enigma"                                   , Character.Enigma               .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Deja Vu"                                  , Character.DejaVu               .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Legendary Deja Vu"                        , Character.DejaVu               .id, Game.TrapTeam       , Deco.Legendary       , variant = true),
            ToyType("Cobra Cadabra"                            , Character.CobraCadabra         .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("King Cobra Cadabra"                       , Character.CobraCadabra         .id, Game.TrapTeam       , Deco.Alternate       , variant = true),
            ToyType("Jawbreaker"                               , Character.Jawbreaker           .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Legendary Jawbreaker"                     , Character.Jawbreaker           .id, Game.TrapTeam       , Deco.Legendary       , variant = true),
            ToyType("Gearshift"                                , Character.Gearshift            .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Chopper"                                  , Character.Chopper              .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Tread Head"                               , Character.TreadHead            .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Bushwhack"                                , Character.Bushwhack            .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Legendary Bushwhack"                      , Character.Bushwhack            .id, Game.TrapTeam       , Deco.Legendary       , variant = true),
            ToyType("Tuff Luck"                                , Character.TuffLuck             .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Clear Tuff Luck"                          , Character.TuffLuck             .id, Game.TrapTeam       , Deco.TreasureHunt2014),
            ToyType("Food Fight"                               , Character.FoodFight            .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Dark Food Fight"                          , Character.FoodFight            .id, Game.TrapTeam       , Deco.Alternate       , variant = true),
            ToyType("High Five"                                , Character.HighFive             .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Krypt King"                               , Character.KryptKing            .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Nitro Krypt King"                         , Character.KryptKing            .id, Game.TrapTeam       , Deco.Alternate       , variant = true),
            ToyType("Short Cut"                                , Character.ShortCut             .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Clear Short Cut"                          , Character.ShortCut             .id, Game.TrapTeam       , Deco.TreasureHunt2014),
            ToyType("Bat Spin"                                 , Character.BatSpin              .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Funny Bone"                               , Character.FunnyBone            .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Knight Light"                             , Character.KnightLight          .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Spotlight"                                , Character.SpotLight            .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Knight Mare"                              , Character.KnightMare           .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Blackout"                                 , Character.Blackout             .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Bop Mini"                                 , Character.Bop                  .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Spry Mini"                                , Character.Spry                 .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Hijinx Mini"                              , Character.Hijinx               .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Terrabite Mini"                           , Character.Terrabite            .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Breeze Mini"                              , Character.Breeze               .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Weeruptor Mini"                           , Character.Weerupter            .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Eggsellent Weeruptor Mini"                , Character.Weerupter            .id, Game.TrapTeam       , Deco.Alternate       , variant = true),
            ToyType("Pet Vac Mini"                             , Character.PetVac               .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Power Punch Pet-Vac Mini"                 , Character.PetVac               .id, Game.TrapTeam       , Deco.Alternate       , variant = true),
            ToyType("Small Fry Mini"                           , Character.SmallFry             .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Drobit Mini"                              , Character.Drobit               .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Gill Runt Mini"                           , Character.GillRunt             .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Trigger Snappy Mini"                      , Character.TriggerSnappy        .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Whisper Elf Mini"                         , Character.WhisperElf           .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Barkley Mini"                             , Character.Barkely              .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Gnarly Barkley Mini"                      , Character.Barkely              .id, Game.TrapTeam       , Deco.Alternate       , variant = true),
            ToyType("Thumpling Mini"                           , Character.Thumpling            .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Mini Jini Mini"                           , Character.MiniJini             .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Eye Small Mini"                           , Character.EyeSmall             .id, Game.TrapTeam       , Deco.Normal          ),
            ToyType("Hog Wild Fryno (Series 2)"                , Character.Fyno                 .id, Game.TrapTeam       , Deco.Repose1         , repose = true),
            ToyType("Eon's Elite Dino-Rang"                    , Character.DinoRang             .id, Game.SuperChargers  , Deco.Premium         , repose = true),
            ToyType("Eon's Elite Slam Bam"                     , Character.SlamBam              .id, Game.SuperChargers  , Deco.Premium         , repose = true),
            ToyType("Eon's Elite Voodood"                      , Character.Voodood              .id, Game.SuperChargers  , Deco.Premium         , repose = true),
            ToyType("Eon's Elite Boomer"                       , Character.Boomer               .id, Game.SuperChargers  , Deco.Premium         , repose = true),
            ToyType("Eon's Elite Zook"                         , Character.Zook                 .id, Game.SuperChargers  , Deco.Premium         , repose = true),
            ToyType("Eon's Elite Ghost Roaster"                , Character.GhostRoaster         .id, Game.SuperChargers  , Deco.Premium         , repose = true),
            ToyType("Jet Stream"                               , Character.AirJet               .id, Game.SuperChargers  , Deco.Normal          ),
            ToyType("Tomb Buggy"                               , Character.UndeadBuggy          .id, Game.SuperChargers  , Deco.Normal          ),
            ToyType("Bronze Tomb Buggy"                        , Character.UndeadBuggy          .id, Game.SuperChargers  , Deco.TreasureHunt2015),
            ToyType("Reef Ripper"                              , Character.WaterFishSub         .id, Game.SuperChargers  , Deco.Normal          ),
            ToyType("Burn-Cycle"                               , Character.FireBike             .id, Game.SuperChargers  , Deco.Normal          ),
            ToyType("Patina Burn-Cycle"                        , Character.FireBike             .id, Game.SuperChargers  , Deco.TreasureHunt2015),
            ToyType("Hot Streak"                               , Character.FireCar              .id, Game.SuperChargers  , Deco.Normal          ),
            ToyType("E3 Hot Streak"                            , Character.FireCar              .id, Game.SuperChargers  , Deco.Event           ),
            ToyType("Mobile Hot Streak (Special)"              , Character.FireCar              .id, Game.SuperChargers  , Deco.Mobile          , supercharger = true),
            ToyType("Dark Hot Streak"                          , Character.FireCar              .id, Game.SuperChargers  , Deco.Alternate       , variant = true),
            ToyType("Golden Hot Streak"                        , Character.FireCar              .id, Game.SuperChargers  , Deco.TreasureHunt2015, variant = true),
            ToyType("Instant Hot Streak"                       , Character.FireCar              .id, Game.SuperChargers  , Deco.Virtual         , variant = true, supercharger = true),
            ToyType("Shark Tank"                               , Character.EarthTank            .id, Game.SuperChargers  , Deco.Normal          ),
            ToyType("Thump Truck"                              , Character.EarthTruck           .id, Game.SuperChargers  , Deco.Normal          ),
            ToyType("Crypt Crusher"                            , Character.UndeadCar            .id, Game.SuperChargers  , Deco.Normal          ),
            ToyType("Stealth Stinger"                          , Character.LifeCopter           .id, Game.SuperChargers  , Deco.Normal          ),
            ToyType("Nitro Stealth Stinger"                    , Character.LifeCopter           .id, Game.SuperChargers  , Deco.Alternate       , variant = true),
            ToyType("Instant Stealth Stinger"                  , Character.LifeCopter           .id, Game.SuperChargers  , Deco.Virtual         , variant = true, supercharger = true),
            ToyType("Dive Bomber"                              , Character.WaterTorpedoSub      .id, Game.SuperChargers  , Deco.Normal          ),
            ToyType("Spring Ahead Dive Bomber"                 , Character.WaterTorpedoSub      .id, Game.SuperChargers  , Deco.Alternate       , variant = true),
            ToyType("Instant Dive Bomber"                      , Character.WaterTorpedoSub      .id, Game.SuperChargers  , Deco.Virtual         , variant = true, supercharger = true),
            ToyType("Sky Slicer"                               , Character.AirPlane             .id, Game.SuperChargers  , Deco.Normal          ),
            ToyType("Clown Cruiser"                            , Character.ClownPlane           .id, Game.SuperChargers  , Deco.Normal          ),
            ToyType("Dark Clown Cruiser"                       , Character.ClownPlane           .id, Game.SuperChargers  , Deco.Alternate       , variant = true),
            ToyType("Gold Rusher"                              , Character.TechBike             .id, Game.SuperChargers  , Deco.Normal          ),
            ToyType("Power Blue Gold Rusher"                   , Character.TechBike             .id, Game.SuperChargers  , Deco.Alternate       , variant = true),
            ToyType("Shield Striker"                           , Character.TechTruck            .id, Game.SuperChargers  , Deco.Normal          ),
            ToyType("Patina Shield Striker"                    , Character.TechTruck            .id, Game.SuperChargers  , Deco.TreasureHunt2015),
            ToyType("Sun Runner"                               , Character.LightPlane           .id, Game.SuperChargers  , Deco.Normal          ),
            ToyType("Legendary Sun Runner"                     , Character.LightPlane           .id, Game.SuperChargers  , Deco.Legendary       , variant = true),
            ToyType("Sea Shadow"                               , Character.DarkMantaSub         .id, Game.SuperChargers  , Deco.Normal          ),
            ToyType("Dark Sea Shadow"                          , Character.DarkMantaSub         .id, Game.SuperChargers  , Deco.Alternate       , variant = true),
            ToyType("Splatter Splasher"                        , Character.MagicSub             .id, Game.SuperChargers  , Deco.Normal          ),
            ToyType("Power Blue Splatter Splasher"             , Character.MagicSub             .id, Game.SuperChargers  , Deco.Alternate       , variant = true),
            ToyType("Soda Skimmer"                             , Character.MagicFloat           .id, Game.SuperChargers  , Deco.Normal          ),
            ToyType("Nitro Soda Skimmer"                       , Character.MagicFloat           .id, Game.SuperChargers  , Deco.Alternate       , variant = true),
            ToyType("Barrel Blaster"                           , Character.DKCart               .id, Game.SuperChargers  , Deco.Normal          ),
            ToyType("Dark Barrel Blaster"                      , Character.DKCart               .id, Game.SuperChargers  , Deco.Alternate       , variant = true),
            ToyType("Buzz Wing"                                , Character.LifePlane            .id, Game.SuperChargers  , Deco.Normal          ),
            ToyType("Fiesta"                                   , Character.SoulJam              .id, Game.SuperChargers  , Deco.Normal          , supercharger = true),
            ToyType("Frightful Fiesta"                         , Character.SoulJam              .id, Game.SuperChargers  , Deco.Halloween       , variant = true, supercharger = true),
            ToyType("High Volt"                                , Character.Lightbulb            .id, Game.SuperChargers  , Deco.Normal          , supercharger = true),
            ToyType("Patina High Volt"                         , Character.Lightbulb            .id, Game.SuperChargers  , Deco.TreasureHunt2015, supercharger = true),
            ToyType("Splat"                                    , Character.InkGirl              .id, Game.SuperChargers  , Deco.Normal          , supercharger = true),
            ToyType("Power Blue Splat"                         , Character.InkGirl              .id, Game.SuperChargers  , Deco.Alternate       , variant = true, supercharger = true),
            ToyType("Stormblade"                               , Character.Peacock              .id, Game.SuperChargers  , Deco.Normal          , supercharger = true),
            ToyType("Snow-Brite Stormblade (Employee Edition)" , Character.Peacock              .id, Game.SuperChargers  , Deco.Winter          , supercharger = true),
            ToyType("Smash Hit"                                , Character.Koala                .id, Game.SuperChargers  , Deco.Normal          , supercharger = true),
            ToyType("Steel Plated Smash Hit"                   , Character.Koala                .id, Game.SuperChargers  , Deco.Alternate       , variant = true, supercharger = true),
            ToyType("Spitfire"                                 , Character.Nitro                .id, Game.SuperChargers  , Deco.Normal          , supercharger = true),
            ToyType("Dark Spitfire"                            , Character.Nitro                .id, Game.SuperChargers  , Deco.Alternate       , variant = true, supercharger = true),
            ToyType("Instant Spitfire"                         , Character.Nitro                .id, Game.SuperChargers  , Deco.Virtual         , variant = true, supercharger = true),
            ToyType("Hurricane Jet-Vac"                        , Character.DriverJetVac         .id, Game.SuperChargers  , Deco.Normal          , supercharger = true),
            ToyType("Legendary Hurricane Jet-Vac"              , Character.DriverJetVac         .id, Game.SuperChargers  , Deco.Legendary       , variant = true, supercharger = true),
            ToyType("Double Dare Trigger Happy"                , Character.DriverTriggerHappy   .id, Game.SuperChargers  , Deco.Normal          , supercharger = true),
            ToyType("Power Blue Double Dare Trigger Happy"     , Character.DriverTriggerHappy   .id, Game.SuperChargers  , Deco.Alternate       , variant = true, supercharger = true),
            ToyType("Super Shot Stealth Elf"                   , Character.DriverStealthElf     .id, Game.SuperChargers  , Deco.Normal          , supercharger = true),
            ToyType("Dark Super Shot Stealth Elf"              , Character.DriverStealthElf     .id, Game.SuperChargers  , Deco.Alternate       , variant = true, supercharger = true),
            ToyType("Instant Super Shot Stealth Elf"           , Character.DriverStealthElf     .id, Game.SuperChargers  , Deco.Virtual         , variant = true, supercharger = true),
            ToyType("Shark Shooter Terrafin"                   , Character.DriverTerrafin       .id, Game.SuperChargers  , Deco.Normal          , supercharger = true),
            ToyType("Bone Bash Roller Brawl"                   , Character.DriverRollerBrawl    .id, Game.SuperChargers  , Deco.Normal          , supercharger = true),
            ToyType("Bronze Bone Bash Roller Brawl"            , Character.DriverRollerBrawl    .id, Game.SuperChargers  , Deco.TreasureHunt2015, supercharger = true),
            ToyType("Legendary Bone Bash Roller Brawl"         , Character.DriverRollerBrawl    .id, Game.SuperChargers  , Deco.Legendary       , variant = true, supercharger = true),
            ToyType("Big Bubble Pop Fizz"                      , Character.DriverPopFizz        .id, Game.SuperChargers  , Deco.Normal          , supercharger = true),
            ToyType("Birthday Bash Big Bubble Pop Fizz"        , Character.DriverPopFizz        .id, Game.SuperChargers  , Deco.Winter          , variant = true, supercharger = true),
            ToyType("Lava Lance Eruptor"                       , Character.DriverEruptor        .id, Game.SuperChargers  , Deco.Normal          , supercharger = true),
            ToyType("Patina Lava Lance Eruptor"                , Character.DriverEruptor        .id, Game.SuperChargers  , Deco.TreasureHunt2015, supercharger = true),
            ToyType("Deep Dive Gill Grunt"                     , Character.DriverGillGrunt      .id, Game.SuperChargers  , Deco.Normal          , supercharger = true),
            ToyType("Turbo Charge Donkey Kong"                 , Character.DonkeyKong           .id, Game.SuperChargers  , Deco.Normal          , supercharger = true),
            ToyType("Dark Turbo Charge Donkey Kong"            , Character.DonkeyKong           .id, Game.SuperChargers  , Deco.Alternate       , variant = true, supercharger = true),
            ToyType("Hammer Slam Bowser"                       , Character.Bowser               .id, Game.SuperChargers  , Deco.Normal          , supercharger = true),
            ToyType("Dark Hammer Slam Bowser"                  , Character.Bowser               .id, Game.SuperChargers  , Deco.Alternate       , variant = true, supercharger = true),
            ToyType("Dive-Clops"                               , Character.AirLock              .id, Game.SuperChargers  , Deco.Normal          , supercharger = true),
            ToyType("Missile-Tow Dive-Clops"                   , Character.AirLock              .id, Game.SuperChargers  , Deco.Winter          , variant = true, supercharger = true),
            ToyType("Instant Dive-Clops"                       , Character.AirLock              .id, Game.SuperChargers  , Deco.Virtual         , variant = true, supercharger = true),
            ToyType("Astroblast"                               , Character.LightDriver          .id, Game.SuperChargers  , Deco.Normal          , supercharger = true),
            ToyType("Legendary Astroblast"                     , Character.LightDriver          .id, Game.SuperChargers  , Deco.Legendary       , variant = true, supercharger = true),
            ToyType("Nightfall"                                , Character.DarkDriver           .id, Game.SuperChargers  , Deco.Normal          , supercharger = true),
            ToyType("Thrillipede"                              , Character.LifeBug              .id, Game.SuperChargers  , Deco.Normal          , supercharger = true),
            ToyType("Eggcited Thrillipede"                     , Character.LifeBug              .id, Game.SuperChargers  , Deco.Easter          , variant = true, supercharger = true),
            ToyType("Sky Trophy"                               , Character.SkyTrophy            .id, Game.SuperChargers  , Deco.Normal          ),
            ToyType("Land Trophy"                              , Character.LandTrophy           .id, Game.SuperChargers  , Deco.Normal          ),
            ToyType("Sea Trophy"                               , Character.SeaTrophy            .id, Game.SuperChargers  , Deco.Normal          ),
            ToyType("Kaos Trophy"                              , Character.KaosTrophy           .id, Game.SuperChargers  , Deco.Normal          ),
        )
    }
}