package edu.jorbonism.nfclanders.enums

enum class Trinket(val ord: UByte, val label: String) {
    None                    ( 0u, "None"                      ),
    LuckyTie                ( 1u, "T-Bone's Lucky Tie"        ),
    Bubble                  ( 2u, "Batterson's Bubble"        ),
    DarkWaterDaisy          ( 3u, "Dark Water Daisy"          ),
    VoteForCyclops          ( 4u, "Vote for Cyclops"          ),
    DragonHorn              ( 5u, "Ramses' Dragon Horn"       ),
    Iris                    ( 6u, "Iris' Iris"                ),
    KuckooKazoo             ( 7u, "Kuckoo Kazoo"              ),
    Rune                    ( 8u, "Ramses' Rune"              ),
    UllyssesUniclops        ( 9u, "Ullysses Uniclops"         ),
    BillyBison              (10u, "Billy Bison"               ),
    StealthElfGift          (11u, "Stealth Elf's Gift"        ),
    LizardLilly             (12u, "Lizard Lilly"              ),
    PiratePinwheel          (13u, "Pirate Pinwheel"           ),
    BubbleBlower            (14u, "Bubble Blower"             ),
    MedalOfHeroism          (15u, "Medal of Heroism"          ),
    MedalOfCourage          (16u, "Blobbers' Medal of Courage"),
    MedalOfValiance         (17u, "Medal of Valiance"         ),
    MedalOfGallantry        (18u, "Medal of Gallantry"        ),
    MedalOfMettle           (19u, "Medal of Mettle"           ),
    WingedMedalOfBravery    (20u, "Winged Medal of Bravery"   ),
    SeadogSeashell          (21u, "Seadog Seashell"           ),
    Sunflower               (22u, "Snuckles' Sunflower"       ),
    TeddyCyclops            (23u, "Teddy Cyclops"             ),
    GooFactoryGear          (24u, "Goo Factory Gear"          ),
    ElementalOpal           (25u, "Elemental Opal"            ),
    ElementalRadiant        (26u, "Elemental Radiant"         ),
    ElementalDiamond        (27u, "Elemental Diamond"         ),
    CyclopsSpinner          (28u, "Cyclops Spinner"           ),
    WilikinWindmill         (29u, "Wilikin Windmill"          ),
    TimeTownTicker          (30u, "Time Town Ticker"          ),
    BigBowOfBoom            (31u, "Big Bow of Boom"           ),
    MabusMedallion          (32u, "Mabu's Medallion"          ),
    SpyrosShield            (33u, "Spyro's Shield"            ),
}
